//! Skill manifest parsing and portable SKILL.md helpers.

/// Parsed skill manifest — the structured metadata from SKILL.md frontmatter.
///
/// `name` and `description` are required for a useful skill, but parse-time
/// recovery intentionally defaults missing fields so diagnostics can report
/// malformed skills without failing the whole registry load. This struct is used
/// by the skill builder, the TUI `/skills` command, and setup-time skill loading.
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct SkillManifest {
    /// Kebab-case unique name (e.g., "opportunity-eval").
    pub name: String,
    /// One-line description shown in `/skills list`.
    pub description: String,
    /// Unique identifier (UUID). Auto-generated by the builder.
    #[serde(default)]
    pub id: Option<String>,
    /// Skill version (e.g., "1.0.0"). For user tracking, not enforced.
    #[serde(default)]
    pub version: Option<String>,
    /// Discovery/filtering tags (e.g., ["govcon", "research"]).
    #[serde(default)]
    pub tags: Vec<String>,
    /// Alternative invocation names (e.g., ["eval", "opp"]).
    #[serde(default)]
    pub aliases: Vec<String>,
    /// Phrases that trigger this skill (e.g., "evaluate this opportunity").
    #[serde(default)]
    pub triggers: Vec<String>,
    /// Activation policy hint: always, intent_detected, project_detected,
    /// domain_detected, or lifecycle_gated.
    #[serde(default)]
    pub activation: Option<String>,
    /// Profile buckets where this skill is relevant (e.g., coding, docs).
    #[serde(default)]
    pub profile: Vec<String>,
    /// Files/globs that suggest this skill should be active.
    #[serde(default)]
    pub project_signals: Vec<String>,
    /// Paths outside the workspace this skill needs access to.
    /// Auto-trusted on session startup and persisted to settings.
    #[serde(default)]
    pub trusted_paths: Vec<String>,
    /// Where results should be written.
    #[serde(default)]
    pub output_path: Option<String>,
    /// Output format hint: "markdown", "json", etc.
    #[serde(default)]
    pub output_format: Option<String>,
    /// Recommended max_turns override for this skill.
    #[serde(default)]
    pub max_turns: Option<u32>,
    /// Recommended posture (e.g., "architect", "fabricator").
    #[serde(default)]
    pub posture: Option<String>,
}

impl SkillManifest {
    /// Render this manifest as YAML frontmatter for a portable SKILL.md file.
    ///
    /// YAML is Omegon's canonical skill frontmatter format because it matches
    /// the de facto cross-agent SKILL.md ecosystem. TOML frontmatter remains
    /// accepted by the parser for existing Omegon skills and local preference.
    pub fn to_frontmatter(&self) -> String {
        let yaml = serde_yaml::to_string(self)
            .unwrap_or_else(|_| "name: ''\ndescription: ''\n".to_string());
        format!("---\n{}---", yaml)
    }

    /// Generate a complete SKILL.md file from this manifest and a body.
    pub fn to_skill_file(&self, body: &str) -> String {
        format!("{}\n\n{}", self.to_frontmatter(), body)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FrontmatterFormat {
    Yaml,
    Toml,
}

/// Parse a SKILL.md into its manifest and body text.
pub fn parse_skill_file(content: &str) -> (SkillManifest, String) {
    let (frontmatter, body) = split_frontmatter(content);
    let manifest = match frontmatter {
        Some((FrontmatterFormat::Yaml, fm)) => serde_yaml::from_str::<SkillManifest>(&fm)
            .or_else(|_| toml::from_str::<SkillManifest>(&fm))
            .unwrap_or_default(),
        Some((FrontmatterFormat::Toml, fm)) => toml::from_str::<SkillManifest>(&fm)
            .or_else(|_| serde_yaml::from_str::<SkillManifest>(&fm))
            .unwrap_or_default(),
        None => SkillManifest::default(),
    };
    (manifest, body.to_string())
}

/// Split a SKILL.md file into raw frontmatter and body.
///
/// Most callers should use [`parse_skill_file`]. This lower-level helper is
/// public for diagnostics/tests that need to preserve the raw delimiter format.
pub fn split_frontmatter(content: &str) -> (Option<(FrontmatterFormat, String)>, &str) {
    let (rest, delimiter, format) = if let Some(b) = content.strip_prefix("+++\n") {
        (b, "\n+++", FrontmatterFormat::Toml)
    } else if let Some(b) = content.strip_prefix("---\n") {
        (b, "\n---", FrontmatterFormat::Yaml)
    } else {
        return (None, content);
    };
    match rest.find(delimiter) {
        Some(end) => {
            let fm = &rest[..end];
            let body = &rest[end + delimiter.len()..];
            let body = body.strip_prefix('\n').unwrap_or(body);
            (Some((format, fm.to_string())), body)
        }
        None => (None, content),
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SkillActivation {
    Always,
    IntentDetected,
    ProjectDetected,
    DomainDetected,
    LifecycleGated,
}

impl SkillActivation {
    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "always" => Some(Self::Always),
            "intent_detected" => Some(Self::IntentDetected),
            "project_detected" => Some(Self::ProjectDetected),
            "domain_detected" => Some(Self::DomainDetected),
            "lifecycle_gated" => Some(Self::LifecycleGated),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SkillProfile {
    Coding,
    Lifecycle,
    Docs,
    Infra,
    Design,
}

impl SkillProfile {
    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "coding" => Some(Self::Coding),
            "lifecycle" => Some(Self::Lifecycle),
            "docs" => Some(Self::Docs),
            "infra" => Some(Self::Infra),
            "design" => Some(Self::Design),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkillActivationDiagnostics {
    pub activation: Option<SkillActivation>,
    pub profiles: Vec<SkillProfile>,
    pub warnings: Vec<String>,
}

pub fn validate_activation_metadata(manifest: &SkillManifest) -> SkillActivationDiagnostics {
    let mut warnings = Vec::new();
    let activation = manifest.activation.as_deref().and_then(|value| {
        let parsed = SkillActivation::parse(value);
        if parsed.is_none() {
            warnings.push(format!("unknown activation '{value}'"));
        }
        parsed
    });

    let mut profiles = Vec::new();
    for profile in &manifest.profile {
        if let Some(parsed) = SkillProfile::parse(profile) {
            profiles.push(parsed);
        } else {
            warnings.push(format!("unknown profile '{profile}'"));
        }
    }

    if matches!(
        activation,
        Some(SkillActivation::ProjectDetected | SkillActivation::DomainDetected)
    ) && manifest.project_signals.is_empty()
    {
        warnings.push("project/domain detected skill has no project_signals".into());
    }
    if activation == Some(SkillActivation::LifecycleGated)
        && !profiles.contains(&SkillProfile::Lifecycle)
    {
        warnings.push("lifecycle-gated skill does not include lifecycle profile".into());
    }
    if activation == Some(SkillActivation::Always) && manifest.profile.is_empty() {
        warnings.push("always activation is profile-scoped but no profile is declared".into());
    }

    SkillActivationDiagnostics {
        activation,
        profiles,
        warnings,
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SkillAdaptationKind {
    NotAdapted,
    PromptOnlyAdaptation,
    CleanRoomAdaptation,
    TrustedExecutableImport,
    ExactImport,
}

pub fn classify_skill_adaptation(body: &str) -> SkillAdaptationKind {
    let lower = body.to_ascii_lowercase();
    if lower.contains("clean-room adaptation") || lower.contains("clean-room rewrite") {
        SkillAdaptationKind::CleanRoomAdaptation
    } else if lower.contains("trusted executable import") || lower.contains("trust-and-import") {
        SkillAdaptationKind::TrustedExecutableImport
    } else if lower.contains("exact import") {
        SkillAdaptationKind::ExactImport
    } else if lower.contains("prompt/resources-only adaptation")
        || lower.contains("prompt-only adaptation")
        || lower.contains("## provenance")
    {
        SkillAdaptationKind::PromptOnlyAdaptation
    } else {
        SkillAdaptationKind::NotAdapted
    }
}

fn has_section(body: &str, section: &str) -> bool {
    body.lines()
        .any(|line| line.trim().eq_ignore_ascii_case(section))
}

fn mentions_executable_tooling(body: &str) -> bool {
    let lower = body.to_ascii_lowercase();
    [
        "npm",
        "pnpm",
        "yarn",
        "node_modules",
        "package.json",
        "scripts/",
        "#!/bin/sh",
        "#!/usr/bin/env bash",
        "```sh",
        "```bash",
    ]
    .iter()
    .any(|needle| lower.contains(needle))
}

pub fn adapted_skill_warnings(body: &str) -> Vec<String> {
    let kind = classify_skill_adaptation(body);
    let mut warnings = Vec::new();
    if kind == SkillAdaptationKind::NotAdapted && !mentions_executable_tooling(body) {
        return warnings;
    }
    if kind != SkillAdaptationKind::NotAdapted {
        for section in ["## Provenance", "## Adaptation Notes", "## Safety Notes"] {
            if !has_section(body, section) {
                warnings.push(format!(
                    "adapted skill missing required section `{section}`"
                ));
            }
        }
    }
    if kind == SkillAdaptationKind::CleanRoomAdaptation {
        for section in ["## Omitted Upstream Assets", "## Clean-room Rewrite Notes"] {
            if !has_section(body, section) {
                warnings.push(format!(
                    "clean-room adapted skill missing required section `{section}`"
                ));
            }
        }
    }
    if mentions_executable_tooling(body) && kind == SkillAdaptationKind::NotAdapted {
        warnings.push(
            "skill mentions executable/tooling assets without explicit adaptation trust posture"
                .into(),
        );
    }
    warnings
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SkillSignalKind {
    Literal,
    RootGlob,
    RecursiveGlob,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkillSignalMatch {
    pub signal: String,
    pub matched_path: String,
    pub kind: SkillSignalKind,
}

const IGNORED_SIGNAL_DIRS: &[&str] = &[".git", "target", "node_modules", ".venv", "dist", "build"];

/// Validate and classify a project signal from skill frontmatter.
///
/// Signals are intentionally constrained to workspace-relative literals, root
/// globs like `*.rs`, or one-recursive-segment globs like `docs/**/*.md`.
pub fn validate_project_signal(signal: &str) -> anyhow::Result<SkillSignalKind> {
    if signal.is_empty()
        || signal.starts_with('/')
        || signal.contains('\\')
        || signal.contains('\0')
        || signal
            .split('/')
            .any(|part| part.is_empty() || part == "..")
    {
        anyhow::bail!("invalid project signal '{signal}'");
    }

    if signal.contains("**") {
        if !signal.contains("**/") || signal.matches("**").count() > 1 {
            anyhow::bail!("invalid recursive project signal '{signal}'");
        }
        Ok(SkillSignalKind::RecursiveGlob)
    } else if signal.contains('*') {
        if signal.contains('/') {
            anyhow::bail!("root glob project signal must not contain '/': '{signal}'");
        }
        Ok(SkillSignalKind::RootGlob)
    } else {
        Ok(SkillSignalKind::Literal)
    }
}

/// Match a validated project signal against a workspace root.
///
/// Ignored dependency/build directories are skipped for glob searches to avoid
/// activating skills from vendor or build artifacts.
pub fn match_project_signal(
    root: &std::path::Path,
    signal: &str,
) -> anyhow::Result<Option<SkillSignalMatch>> {
    let kind = validate_project_signal(signal)?;
    let matched = match kind {
        SkillSignalKind::Literal => {
            let candidate = root.join(signal);
            candidate.exists().then_some(signal.to_string())
        }
        SkillSignalKind::RootGlob => std::fs::read_dir(root).ok().and_then(|entries| {
            entries.filter_map(|entry| entry.ok()).find_map(|entry| {
                let name = entry.file_name().to_string_lossy().to_string();
                (glob_component_matches(signal, &name) && !is_ignored_signal_dir(&name))
                    .then_some(name)
            })
        }),
        SkillSignalKind::RecursiveGlob => match_recursive_signal(root, signal)?,
    };

    Ok(matched.map(|matched_path| SkillSignalMatch {
        signal: signal.to_string(),
        matched_path,
        kind,
    }))
}

fn match_recursive_signal(root: &std::path::Path, signal: &str) -> anyhow::Result<Option<String>> {
    let Some((prefix, suffix)) = signal.split_once("**/") else {
        return Ok(None);
    };
    let prefix = prefix.trim_end_matches('/');
    let search_root = if prefix.is_empty() {
        root.to_path_buf()
    } else {
        if prefix.split('/').any(is_ignored_signal_dir) {
            return Ok(None);
        }
        root.join(prefix)
    };
    if !search_root.exists() {
        return Ok(None);
    }
    find_recursive_signal_match(root, &search_root, suffix)
}

fn find_recursive_signal_match(
    root: &std::path::Path,
    dir: &std::path::Path,
    suffix_pattern: &str,
) -> anyhow::Result<Option<String>> {
    let mut entries = match std::fs::read_dir(dir) {
        Ok(entries) => entries.filter_map(|entry| entry.ok()).collect::<Vec<_>>(),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(err) => return Err(err.into()),
    };
    entries.sort_by_key(|entry| entry.path());

    for entry in entries {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();
        if path.is_dir() {
            if is_ignored_signal_dir(&name) {
                continue;
            }
            if let Some(found) = find_recursive_signal_match(root, &path, suffix_pattern)? {
                return Ok(Some(found));
            }
        } else if glob_component_matches(suffix_pattern, &name)
            && let Ok(relative) = path.strip_prefix(root)
        {
            return Ok(Some(relative.to_string_lossy().replace('\\', "/")));
        }
    }
    Ok(None)
}

/// Return whether a directory name should be ignored during project-signal glob matching.
pub fn is_ignored_signal_dir(name: &str) -> bool {
    IGNORED_SIGNAL_DIRS.contains(&name)
}

fn glob_component_matches(pattern: &str, value: &str) -> bool {
    if pattern == "*" {
        return true;
    }
    let Some((prefix, suffix)) = pattern.split_once('*') else {
        return pattern == value;
    };
    value.starts_with(prefix) && value.ends_with(suffix)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn manifest_to_skill_file_renders_yaml_frontmatter() {
        let manifest = SkillManifest {
            name: "test".into(),
            description: "Test skill".into(),
            ..Default::default()
        };
        let file = manifest.to_skill_file("# My Skill\n\nDo things.\n");
        assert!(file.starts_with("---"));
        assert!(file.contains("name: test"));
        assert!(file.contains("# My Skill"));
    }

    #[test]
    fn parse_skill_file_yaml() {
        let content = "---\nname: test\ndescription: A test\nactivation: project_detected\nprofile: [coding]\nproject_signals: [Cargo.toml]\n---\n\n# Body\n";
        let (manifest, body) = parse_skill_file(content);
        assert_eq!(manifest.name, "test");
        assert_eq!(manifest.description, "A test");
        assert_eq!(manifest.activation, Some("project_detected".into()));
        assert_eq!(manifest.profile, vec!["coding"]);
        assert_eq!(manifest.project_signals, vec!["Cargo.toml"]);
        assert!(body.contains("# Body"));
    }

    #[test]
    fn parse_skill_file_toml() {
        let content = "+++\nname = \"test\"\ndescription = \"A test\"\nversion = \"1.0.0\"\nactivation = \"project_detected\"\nprofile = [\"coding\"]\nproject_signals = [\"Cargo.toml\"]\n+++\n\n# Body\n\nDo things.\n";
        let (manifest, body) = parse_skill_file(content);
        assert_eq!(manifest.name, "test");
        assert_eq!(manifest.description, "A test");
        assert_eq!(manifest.version, Some("1.0.0".into()));
        assert_eq!(manifest.activation, Some("project_detected".into()));
        assert_eq!(manifest.profile, vec!["coding"]);
        assert_eq!(manifest.project_signals, vec!["Cargo.toml"]);
        assert!(body.contains("# Body"));
    }

    #[test]
    fn parse_skill_file_no_frontmatter() {
        let content = "# Just markdown\n\nNo frontmatter here.\n";
        let (manifest, body) = parse_skill_file(content);
        assert_eq!(manifest.name, "");
        assert!(body.contains("Just markdown"));
    }

    #[test]
    fn split_frontmatter_detects_toml_yaml_and_absence() {
        let (fm, body) = split_frontmatter("+++\nname = \"test\"\n+++\n\nBody here.\n");
        assert!(fm.is_some());
        let (format, text) = fm.unwrap();
        assert_eq!(format, FrontmatterFormat::Toml);
        assert!(text.contains("name = \"test\""));
        assert!(body.contains("Body here."));

        let (fm, body) = split_frontmatter("---\nname: test\n---\n\nBody here.\n");
        assert!(fm.is_some());
        let (format, text) = fm.unwrap();
        assert_eq!(format, FrontmatterFormat::Yaml);
        assert!(text.contains("name: test"));
        assert!(body.contains("Body here."));

        let content = "No delimiters here.\n";
        let (fm, body) = split_frontmatter(content);
        assert!(fm.is_none());
        assert_eq!(body, content);
    }

    #[test]
    fn activation_metadata_diagnostics_cover_invalid_and_unsafe_shapes() {
        let invalid = SkillManifest {
            name: "custom".into(),
            description: "Custom skill".into(),
            activation: Some("projectish".into()),
            profile: vec!["codign".into()],
            ..Default::default()
        };
        let diagnostics = validate_activation_metadata(&invalid);
        assert!(diagnostics.activation.is_none());
        assert!(
            diagnostics
                .warnings
                .iter()
                .any(|w| w.contains("unknown activation 'projectish'"))
        );
        assert!(
            diagnostics
                .warnings
                .iter()
                .any(|w| w.contains("unknown profile 'codign'"))
        );

        let project_without_signals = SkillManifest {
            name: "custom".into(),
            description: "Custom skill".into(),
            activation: Some("project_detected".into()),
            profile: vec!["coding".into()],
            ..Default::default()
        };
        let diagnostics = validate_activation_metadata(&project_without_signals);
        assert_eq!(
            diagnostics.activation,
            Some(SkillActivation::ProjectDetected)
        );
        assert!(diagnostics.profiles.contains(&SkillProfile::Coding));
        assert!(
            diagnostics
                .warnings
                .iter()
                .any(|w| w.contains("no project_signals"))
        );

        let global_always = SkillManifest {
            name: "custom".into(),
            description: "Custom skill".into(),
            activation: Some("always".into()),
            ..Default::default()
        };
        let diagnostics = validate_activation_metadata(&global_always);
        assert_eq!(diagnostics.activation, Some(SkillActivation::Always));
        assert!(
            diagnostics
                .warnings
                .iter()
                .any(|w| w.contains("profile-scoped"))
        );
    }

    #[test]
    fn project_signal_matching_supports_literals_root_globs_and_recursive_globs() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::write(root.join("Cargo.toml"), "").unwrap();
        std::fs::write(root.join("main.rs"), "").unwrap();
        std::fs::create_dir_all(root.join("docs/nested")).unwrap();
        std::fs::write(root.join("docs/nested/guide.md"), "").unwrap();
        std::fs::create_dir_all(root.join("target/generated")).unwrap();
        std::fs::write(root.join("target/generated/ignored.md"), "").unwrap();

        let cargo = match_project_signal(root, "Cargo.toml").unwrap().unwrap();
        assert_eq!(cargo.kind, SkillSignalKind::Literal);
        assert_eq!(cargo.matched_path, "Cargo.toml");

        let rust = match_project_signal(root, "*.rs").unwrap().unwrap();
        assert_eq!(rust.kind, SkillSignalKind::RootGlob);
        assert_eq!(rust.matched_path, "main.rs");

        let docs = match_project_signal(root, "docs/**/*.md").unwrap().unwrap();
        assert_eq!(docs.kind, SkillSignalKind::RecursiveGlob);
        assert_eq!(docs.matched_path, "docs/nested/guide.md");

        assert!(
            match_project_signal(root, "target/**/*.md")
                .unwrap()
                .is_none()
        );
    }

    #[test]
    fn project_signal_validation_rejects_traversal_and_broad_recursive_shapes() {
        for signal in [
            "",
            "/tmp/file",
            "../Cargo.toml",
            "foo/../bar",
            "foo//bar",
            "foo\\bar",
            "**",
            "foo/**/bar/**/baz",
        ] {
            assert!(
                validate_project_signal(signal).is_err(),
                "{signal} should be rejected"
            );
        }
    }

    #[test]
    fn adapted_skill_warnings_cover_provenance_and_executable_posture() {
        assert!(adapted_skill_warnings("# Normal Skill\n\nNo upstream provenance.").is_empty());

        let missing = adapted_skill_warnings("## Provenance\nSource: upstream\n");
        assert!(
            missing.iter().any(|w| w.contains("## Adaptation Notes")),
            "{missing:?}"
        );
        assert!(
            missing.iter().any(|w| w.contains("## Safety Notes")),
            "{missing:?}"
        );

        let clean_missing = adapted_skill_warnings(
            "## Provenance\nKind: clean-room adaptation\n## Adaptation Notes\nNotes\n## Safety Notes\nSafe\n",
        );
        assert!(
            clean_missing
                .iter()
                .any(|w| w.contains("## Omitted Upstream Assets")),
            "{clean_missing:?}"
        );
        assert!(
            clean_missing
                .iter()
                .any(|w| w.contains("## Clean-room Rewrite Notes")),
            "{clean_missing:?}"
        );

        let executable_missing = adapted_skill_warnings("Run npm install from package.json");
        assert!(
            executable_missing
                .iter()
                .any(|w| w.contains("without explicit adaptation trust posture")),
            "{executable_missing:?}"
        );

        let complete_clean = adapted_skill_warnings(
            "## Provenance\nKind: clean-room adaptation\n## Adaptation Notes\nNotes\n## Safety Notes\nSafe\n## Omitted Upstream Assets\n- package.json\n## Clean-room Rewrite Notes\nRewritten without npm.\n",
        );
        assert!(complete_clean.is_empty(), "{complete_clean:?}");

        let trusted = adapted_skill_warnings(
            "## Provenance\nKind: trusted executable import\n## Adaptation Notes\nNotes\n## Safety Notes\nOperator trusts package.json.\nRun npm install.\n",
        );
        assert!(trusted.is_empty(), "{trusted:?}");
    }
}
