//! Skill manifest parsing and portable SKILL.md helpers.

/// Parsed skill manifest — the structured metadata from SKILL.md frontmatter.
///
/// `name` and `description` are required for a useful skill, but parse-time
/// recovery intentionally defaults missing fields so diagnostics can report
/// malformed skills without failing the whole registry load. This struct is used
/// by the skill builder, the TUI `/skills` command, and setup-time skill loading.
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct SkillManifest {
    /// Kebab-case unique name (e.g., "opportunity-eval").
    pub name: String,
    /// One-line description shown in `/skills list`.
    pub description: String,
    /// Unique identifier (UUID). Auto-generated by the builder.
    #[serde(default)]
    pub id: Option<String>,
    /// Skill version (e.g., "1.0.0"). For user tracking, not enforced.
    #[serde(default)]
    pub version: Option<String>,
    /// Discovery/filtering tags (e.g., ["govcon", "research"]).
    #[serde(default)]
    pub tags: Vec<String>,
    /// Alternative invocation names (e.g., ["eval", "opp"]).
    #[serde(default)]
    pub aliases: Vec<String>,
    /// Phrases that trigger this skill (e.g., "evaluate this opportunity").
    #[serde(default)]
    pub triggers: Vec<String>,
    /// Activation policy hint: always, intent_detected, project_detected,
    /// domain_detected, or lifecycle_gated.
    #[serde(default)]
    pub activation: Option<String>,
    /// Profile buckets where this skill is relevant (e.g., coding, docs).
    #[serde(default)]
    pub profile: Vec<String>,
    /// Files/globs that suggest this skill should be active.
    #[serde(default)]
    pub project_signals: Vec<String>,
    /// Paths outside the workspace this skill needs access to.
    /// Auto-trusted on session startup and persisted to settings.
    #[serde(default)]
    pub trusted_paths: Vec<String>,
    /// Where results should be written.
    #[serde(default)]
    pub output_path: Option<String>,
    /// Output format hint: "markdown", "json", etc.
    #[serde(default)]
    pub output_format: Option<String>,
    /// Recommended max_turns override for this skill.
    #[serde(default)]
    pub max_turns: Option<u32>,
    /// Recommended posture (e.g., "architect", "fabricator").
    #[serde(default)]
    pub posture: Option<String>,
}

impl SkillManifest {
    /// Render this manifest as YAML frontmatter for a portable SKILL.md file.
    ///
    /// YAML is Omegon's canonical skill frontmatter format because it matches
    /// the de facto cross-agent SKILL.md ecosystem. TOML frontmatter remains
    /// accepted by the parser for existing Omegon skills and local preference.
    pub fn to_frontmatter(&self) -> String {
        let yaml = serde_yaml::to_string(self)
            .unwrap_or_else(|_| "name: ''\ndescription: ''\n".to_string());
        format!("---\n{}---", yaml)
    }

    /// Generate a complete SKILL.md file from this manifest and a body.
    pub fn to_skill_file(&self, body: &str) -> String {
        format!("{}\n\n{}", self.to_frontmatter(), body)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FrontmatterFormat {
    Yaml,
    Toml,
}

/// Parse a SKILL.md into its manifest and body text.
pub fn parse_skill_file(content: &str) -> (SkillManifest, String) {
    let (frontmatter, body) = split_frontmatter(content);
    let manifest = match frontmatter {
        Some((FrontmatterFormat::Yaml, fm)) => serde_yaml::from_str::<SkillManifest>(&fm)
            .or_else(|_| toml::from_str::<SkillManifest>(&fm))
            .unwrap_or_default(),
        Some((FrontmatterFormat::Toml, fm)) => toml::from_str::<SkillManifest>(&fm)
            .or_else(|_| serde_yaml::from_str::<SkillManifest>(&fm))
            .unwrap_or_default(),
        None => SkillManifest::default(),
    };
    (manifest, body.to_string())
}

/// Split a SKILL.md file into raw frontmatter and body.
///
/// Most callers should use [`parse_skill_file`]. This lower-level helper is
/// public for diagnostics/tests that need to preserve the raw delimiter format.
pub fn split_frontmatter(content: &str) -> (Option<(FrontmatterFormat, String)>, &str) {
    let (rest, delimiter, format) = if let Some(b) = content.strip_prefix("+++\n") {
        (b, "\n+++", FrontmatterFormat::Toml)
    } else if let Some(b) = content.strip_prefix("---\n") {
        (b, "\n---", FrontmatterFormat::Yaml)
    } else {
        return (None, content);
    };
    match rest.find(delimiter) {
        Some(end) => {
            let fm = &rest[..end];
            let body = &rest[end + delimiter.len()..];
            let body = body.strip_prefix('\n').unwrap_or(body);
            (Some((format, fm.to_string())), body)
        }
        None => (None, content),
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SkillActivation {
    Always,
    IntentDetected,
    ProjectDetected,
    DomainDetected,
    LifecycleGated,
}

impl SkillActivation {
    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "always" => Some(Self::Always),
            "intent_detected" => Some(Self::IntentDetected),
            "project_detected" => Some(Self::ProjectDetected),
            "domain_detected" => Some(Self::DomainDetected),
            "lifecycle_gated" => Some(Self::LifecycleGated),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SkillProfile {
    Coding,
    Lifecycle,
    Docs,
    Infra,
    Design,
}

impl SkillProfile {
    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "coding" => Some(Self::Coding),
            "lifecycle" => Some(Self::Lifecycle),
            "docs" => Some(Self::Docs),
            "infra" => Some(Self::Infra),
            "design" => Some(Self::Design),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkillActivationDiagnostics {
    pub activation: Option<SkillActivation>,
    pub profiles: Vec<SkillProfile>,
    pub warnings: Vec<String>,
}

pub fn validate_activation_metadata(manifest: &SkillManifest) -> SkillActivationDiagnostics {
    let mut warnings = Vec::new();
    let activation = manifest.activation.as_deref().and_then(|value| {
        let parsed = SkillActivation::parse(value);
        if parsed.is_none() {
            warnings.push(format!("unknown activation '{value}'"));
        }
        parsed
    });

    let mut profiles = Vec::new();
    for profile in &manifest.profile {
        if let Some(parsed) = SkillProfile::parse(profile) {
            profiles.push(parsed);
        } else {
            warnings.push(format!("unknown profile '{profile}'"));
        }
    }

    if matches!(
        activation,
        Some(SkillActivation::ProjectDetected | SkillActivation::DomainDetected)
    ) && manifest.project_signals.is_empty()
    {
        warnings.push("project/domain detected skill has no project_signals".into());
    }
    if activation == Some(SkillActivation::LifecycleGated)
        && !profiles.contains(&SkillProfile::Lifecycle)
    {
        warnings.push("lifecycle-gated skill does not include lifecycle profile".into());
    }
    if activation == Some(SkillActivation::Always) && manifest.profile.is_empty() {
        warnings.push("always activation is profile-scoped but no profile is declared".into());
    }

    SkillActivationDiagnostics {
        activation,
        profiles,
        warnings,
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SkillAdaptationKind {
    NotAdapted,
    PromptOnlyAdaptation,
    CleanRoomAdaptation,
    TrustedExecutableImport,
    ExactImport,
}

pub fn classify_skill_adaptation(body: &str) -> SkillAdaptationKind {
    let lower = body.to_ascii_lowercase();
    if lower.contains("clean-room adaptation") || lower.contains("clean-room rewrite") {
        SkillAdaptationKind::CleanRoomAdaptation
    } else if lower.contains("trusted executable import") || lower.contains("trust-and-import") {
        SkillAdaptationKind::TrustedExecutableImport
    } else if lower.contains("exact import") {
        SkillAdaptationKind::ExactImport
    } else if lower.contains("prompt/resources-only adaptation")
        || lower.contains("prompt-only adaptation")
        || lower.contains("## provenance")
    {
        SkillAdaptationKind::PromptOnlyAdaptation
    } else {
        SkillAdaptationKind::NotAdapted
    }
}

fn has_section(body: &str, section: &str) -> bool {
    body.lines()
        .any(|line| line.trim().eq_ignore_ascii_case(section))
}

fn mentions_executable_tooling(body: &str) -> bool {
    let lower = body.to_ascii_lowercase();
    [
        "npm",
        "pnpm",
        "yarn",
        "node_modules",
        "package.json",
        "scripts/",
        "#!/bin/sh",
        "#!/usr/bin/env bash",
        "```sh",
        "```bash",
    ]
    .iter()
    .any(|needle| lower.contains(needle))
}

pub fn adapted_skill_warnings(body: &str) -> Vec<String> {
    let kind = classify_skill_adaptation(body);
    let mut warnings = Vec::new();
    if kind == SkillAdaptationKind::NotAdapted && !mentions_executable_tooling(body) {
        return warnings;
    }
    if kind != SkillAdaptationKind::NotAdapted {
        for section in ["## Provenance", "## Adaptation Notes", "## Safety Notes"] {
            if !has_section(body, section) {
                warnings.push(format!(
                    "adapted skill missing required section `{section}`"
                ));
            }
        }
    }
    if kind == SkillAdaptationKind::CleanRoomAdaptation {
        for section in ["## Omitted Upstream Assets", "## Clean-room Rewrite Notes"] {
            if !has_section(body, section) {
                warnings.push(format!(
                    "clean-room adapted skill missing required section `{section}`"
                ));
            }
        }
    }
    if mentions_executable_tooling(body) && kind == SkillAdaptationKind::NotAdapted {
        warnings.push(
            "skill mentions executable/tooling assets without explicit adaptation trust posture"
                .into(),
        );
    }
    warnings
}

/// Extract `trusted_paths` from SKILL.md frontmatter.
///
/// Skills that need to read/write outside the workspace can declare paths
/// in their frontmatter. On session startup, these paths are auto-trusted
/// (added to settings.trusted_directories if not already present), so the
/// user isn't prompted repeatedly.
///
/// YAML format:
/// ```yaml
/// trusted_paths:
///   - ~/Documents/pastperformance/
///   - ~/Library/Mobile Documents/iCloud~md~obsidian/Documents/jaredp/evaluations/
/// ```
///
/// TOML format:
/// ```toml
/// trusted_paths = ["~/Documents/pastperformance/"]
/// ```
pub fn extract_trusted_paths(content: &str) -> Vec<String> {
    let (body, delimiter) = if let Some(b) = content.strip_prefix("---\n") {
        (b, "\n---")
    } else if let Some(b) = content.strip_prefix("+++\n") {
        (b, "\n+++")
    } else {
        return Vec::new();
    };
    let end = match body.find(delimiter) {
        Some(e) => e,
        None => return Vec::new(),
    };
    let frontmatter = &body[..end];

    let mut paths = Vec::new();

    // TOML: trusted_paths = ["path1", "path2"]
    for line in frontmatter.lines() {
        if let Some(rest) = line.strip_prefix("trusted_paths") {
            let rest = rest.trim();
            if let Some(rest) = rest.strip_prefix('=') {
                let rest = rest.trim();
                if rest.starts_with('[') {
                    // Parse simple TOML array: ["path1", "path2"]
                    let inner = rest.trim_start_matches('[').trim_end_matches(']');
                    for item in inner.split(',') {
                        let item = item.trim().trim_matches('"').trim_matches('\'');
                        if !item.is_empty() {
                            paths.push(item.to_string());
                        }
                    }
                }
            }
        }
    }

    // YAML: trusted_paths:\n  - path1\n  - path2
    let mut in_trusted_paths = false;
    for line in frontmatter.lines() {
        if line.starts_with("trusted_paths:") {
            in_trusted_paths = true;
            // Check for inline value: trusted_paths: [path1, path2]
            let rest = line.strip_prefix("trusted_paths:").unwrap().trim();
            if rest.starts_with('[') {
                let inner = rest.trim_start_matches('[').trim_end_matches(']');
                for item in inner.split(',') {
                    let item = item.trim().trim_matches('"').trim_matches('\'');
                    if !item.is_empty() {
                        paths.push(item.to_string());
                    }
                }
                in_trusted_paths = false;
            }
            continue;
        }
        if in_trusted_paths {
            let trimmed = line.trim();
            if let Some(path) = trimmed.strip_prefix("- ") {
                let path = path.trim().trim_matches('"').trim_matches('\'');
                if !path.is_empty() {
                    paths.push(path.to_string());
                }
            } else if !trimmed.is_empty() && !trimmed.starts_with('#') {
                // Not a list item — end of trusted_paths block
                in_trusted_paths = false;
            }
        }
    }

    paths.sort();
    paths.dedup();
    paths
}

/// Collect trusted_paths from all loaded skill content strings.
pub fn collect_trusted_paths(skills: &[String]) -> Vec<String> {
    let mut all_paths = Vec::new();
    for content in skills {
        all_paths.extend(extract_trusted_paths(content));
    }
    all_paths.sort();
    all_paths.dedup();
    all_paths
}

/// Extract phase/step markers from skill content for completion tracking.
///
/// Looks for markdown headings that indicate numbered phases or steps:
///   `## Phase 1:`, `## Phase 2:`, ..., `## Step 1:`, `## Step 2:`, ...
///   `## Phase 0.5:`, `## Phase 1.75:` (fractional phases like in jputman's skill)
///
/// Returns the total number of phases and the label of the final phase
/// (e.g., "Phase 10: Export to File"). Used by the loop to detect
/// premature completion — if the agent declares "done" without reaching
/// the final phase, it gets nudged.
pub fn extract_phase_info(content: &str) -> Option<SkillPhaseInfo> {
    let mut phases: Vec<(String, String)> = Vec::new(); // (number, full heading)

    for line in content.lines() {
        let trimmed = line.trim();
        // Match: ## Phase N: ... or ## Step N: ...
        // Also handles ### Phase N, # Phase N, etc.
        if let Some(rest) = trimmed
            .strip_prefix('#')
            .and_then(|s| {
                s.trim_start_matches('#')
                    .trim_start()
                    .strip_prefix("Phase ")
            })
            .or_else(|| {
                trimmed
                    .strip_prefix('#')
                    .and_then(|s| s.trim_start_matches('#').trim_start().strip_prefix("Step "))
            })
        {
            // Extract the phase number (may be fractional: "0.5", "1.75")
            let num_end = rest
                .find(|c: char| !c.is_ascii_digit() && c != '.')
                .unwrap_or(rest.len());
            let num = &rest[..num_end];
            if !num.is_empty() {
                let heading = trimmed.trim_start_matches('#').trim().to_string();
                phases.push((num.to_string(), heading));
            }
        }
    }

    if phases.is_empty() {
        return None;
    }

    let final_phase = phases.last().unwrap();
    Some(SkillPhaseInfo {
        total_phases: phases.len(),
        final_phase_label: final_phase.1.clone(),
        final_phase_number: final_phase.0.clone(),
    })
}

/// Phase tracking info extracted from a skill's content.
#[derive(Debug, Clone)]
pub struct SkillPhaseInfo {
    /// Total number of phase/step headings found.
    pub total_phases: usize,
    /// The heading text of the final phase (e.g., "Phase 10: Export to File").
    pub final_phase_label: String,
    /// The phase number string (e.g., "10", "1.75").
    pub final_phase_number: String,
}

/// Collect phase info from all loaded skills. Returns info for any skill
/// that has numbered phases (most skills don't — only structured workflows like
/// jputman's opportunity-eval).
pub fn collect_phase_info(skills: &[String]) -> Vec<SkillPhaseInfo> {
    skills
        .iter()
        .filter_map(|s| extract_phase_info(s))
        .collect()
}

/// A resolved skill entry with structured metadata for settings and command surfaces.
#[derive(Debug, Clone, serde::Serialize)]
pub struct SkillEntry {
    pub name: String,
    pub description: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    pub tags: Vec<String>,
    pub aliases: Vec<String>,
    pub triggers: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub activation: Option<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub profile: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub project_signals: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub posture: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_turns: Option<u32>,
    pub installed: bool,
    pub bundled: bool,
    pub project_local: bool,
    /// Provider source for the resolved entry: bundled, user, project, or extension.
    pub source: String,
    /// Whether the operator can edit this skill source directly.
    pub editable: bool,
    /// Whether an explicit skills reload can refresh this source without rebuilding Omegon.
    pub reloadable: bool,
    /// Same-name lower-precedence provider labels shadowed by this entry.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub shadows: Vec<String>,
    /// Non-overriding activation/trigger conflicts with other skills.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub conflicts: Vec<String>,
    pub path: String,
}

#[derive(Debug, Clone)]
pub struct PendingSkillEntry {
    pub entry: SkillEntry,
    pub provider_rank: u8,
}

pub fn skill_entry_provider_rank(source: &str) -> u8 {
    match source {
        "bundled" => 0,
        source if source.starts_with("extension:") => 1,
        "user" => 2,
        "project" => 3,
        _ => 1,
    }
}

pub fn skill_ref(source: &str, name: &str) -> String {
    format!("{source}/{name}")
}

fn normalized_skill_token(value: &str) -> String {
    value.trim().to_ascii_lowercase()
}

fn skill_token_overlap(left: &[String], right: &[String]) -> bool {
    left.iter().any(|left| {
        let left = normalized_skill_token(left);
        !left.is_empty()
            && right
                .iter()
                .any(|right| normalized_skill_token(right) == left)
    })
}

pub fn skill_sources_conflict(a: &SkillEntry, b: &SkillEntry) -> bool {
    if normalized_skill_token(&a.name) == normalized_skill_token(&b.name) {
        return false;
    }
    let trigger_overlap = skill_token_overlap(&a.triggers, &b.triggers);
    let alias_overlap = skill_token_overlap(&a.aliases, &b.aliases);
    let activation_overlap = a.activation.is_some()
        && a.activation == b.activation
        && (!a.profile.is_empty() && a.profile.iter().any(|profile| b.profile.contains(profile))
            || !a.project_signals.is_empty()
                && a.project_signals
                    .iter()
                    .any(|signal| b.project_signals.contains(signal)));
    trigger_overlap || alias_overlap || activation_overlap
}

pub fn finalize_skill_entries(pending: Vec<PendingSkillEntry>) -> Vec<SkillEntry> {
    let mut entries: Vec<SkillEntry> = pending.into_iter().map(|pending| pending.entry).collect();
    for index in 0..entries.len() {
        let conflicts = entries
            .iter()
            .enumerate()
            .filter(|(other_index, other)| {
                *other_index != index && skill_sources_conflict(&entries[index], other)
            })
            .map(|(_, other)| skill_ref(&other.source, &other.name))
            .collect();
        entries[index].conflicts = conflicts;
    }
    entries
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SkillSource {
    Bundled,
    UserInstalled,
    ProjectLocal,
}

#[derive(Debug, Clone)]
pub struct ParsedSkill {
    pub name: String,
    pub manifest: SkillManifest,
    pub source: SkillSource,
    pub path: Option<std::path::PathBuf>,
}

#[derive(Debug, Clone)]
pub struct SkillSuggestion {
    pub name: String,
    pub source: SkillSource,
    pub activation: Option<SkillActivation>,
    pub profiles: Vec<SkillProfile>,
    pub signal_matches: Vec<SkillSignalMatch>,
    pub warnings: Vec<String>,
}

pub struct SkillSuggestionContext<'a> {
    pub root: &'a std::path::Path,
    pub profiles: &'a [SkillProfile],
    pub intent_terms: &'a [&'a str],
}

pub fn suggest_skills_for_context(
    skills: &[ParsedSkill],
    ctx: SkillSuggestionContext<'_>,
) -> Vec<SkillSuggestion> {
    skills
        .iter()
        .filter_map(|skill| suggest_one_skill(skill, &ctx))
        .collect()
}

fn suggest_one_skill(
    skill: &ParsedSkill,
    ctx: &SkillSuggestionContext<'_>,
) -> Option<SkillSuggestion> {
    let diagnostics = validate_activation_metadata(&skill.manifest);
    let intent_matches = skill_intent_matches(skill, ctx.intent_terms);
    let profile_matches = diagnostics
        .profiles
        .iter()
        .any(|profile| ctx.profiles.contains(profile));
    let (signal_matches, signal_warnings) =
        collect_skill_signal_matches(ctx.root, &skill.manifest.project_signals);
    let signal_matched = !signal_matches.is_empty();
    let lifecycle_requested = ctx.profiles.contains(&SkillProfile::Lifecycle)
        || ctx.intent_terms.iter().any(|term| {
            term.eq_ignore_ascii_case("lifecycle") || term.eq_ignore_ascii_case("openspec")
        });

    let mut warnings = diagnostics.warnings.clone();
    warnings.extend(signal_warnings);
    let suggested = match diagnostics.activation {
        Some(SkillActivation::Always) => profile_matches,
        Some(SkillActivation::IntentDetected) => intent_matches,
        Some(SkillActivation::ProjectDetected) => profile_matches && signal_matched,
        Some(SkillActivation::DomainDetected) => {
            (profile_matches || intent_matches) && signal_matched
        }
        Some(SkillActivation::LifecycleGated) => lifecycle_requested && signal_matched,
        None => {
            if skill.manifest.activation.is_none() {
                if intent_matches {
                    warnings.push("activation metadata unspecified".into());
                    true
                } else {
                    false
                }
            } else {
                intent_matches
            }
        }
    };

    suggested.then(|| SkillSuggestion {
        name: skill.name.clone(),
        source: skill.source,
        activation: diagnostics.activation,
        profiles: diagnostics.profiles,
        signal_matches,
        warnings,
    })
}

fn collect_skill_signal_matches(
    root: &std::path::Path,
    signals: &[String],
) -> (Vec<SkillSignalMatch>, Vec<String>) {
    let mut matches = Vec::new();
    let mut warnings = Vec::new();
    for signal in signals {
        match match_project_signal(root, signal) {
            Ok(Some(signal_match)) => matches.push(signal_match),
            Ok(None) => {}
            Err(err) => warnings.push(format!("invalid project_signal '{signal}': {err}")),
        }
    }
    (matches, warnings)
}

fn skill_intent_matches(skill: &ParsedSkill, intent_terms: &[&str]) -> bool {
    intent_terms.iter().any(|term| {
        let term = term.trim();
        !term.is_empty()
            && (skill.name.eq_ignore_ascii_case(term)
                || skill
                    .manifest
                    .tags
                    .iter()
                    .any(|value| value.eq_ignore_ascii_case(term))
                || skill
                    .manifest
                    .aliases
                    .iter()
                    .any(|value| value.eq_ignore_ascii_case(term))
                || skill.manifest.triggers.iter().any(|value| {
                    value
                        .to_ascii_lowercase()
                        .contains(&term.to_ascii_lowercase())
                }))
    })
}

#[derive(Debug, Clone)]
pub struct SkillBundleCandidate {
    pub source: String,
    pub name: String,
    pub path: std::path::PathBuf,
    pub manifest: SkillManifest,
    pub missing_script_refs: Vec<String>,
}

pub fn find_script_references(body: &str) -> Vec<String> {
    let mut refs = Vec::new();
    for token in body
        .split(|ch: char| ch.is_whitespace() || matches!(ch, '`' | '\'' | '"' | ')' | '(' | ','))
    {
        let token = token.trim_matches(|ch: char| matches!(ch, ':' | ';' | '.'));
        if !token.starts_with("scripts/") {
            continue;
        }
        let relative = std::path::Path::new(token);
        if relative.is_absolute()
            || relative.components().any(|component| {
                matches!(
                    component,
                    std::path::Component::ParentDir | std::path::Component::Prefix(_)
                )
            })
        {
            continue;
        }
        if !refs.iter().any(|existing| existing == token) {
            refs.push(token.to_string());
        }
    }
    refs
}

pub fn discover_skill_bundles(
    source: &str,
    root: &std::path::Path,
) -> anyhow::Result<Vec<SkillBundleCandidate>> {
    if !root.is_dir() {
        return Ok(Vec::new());
    }
    let mut bundles = Vec::new();
    let mut stack = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let skill_file = dir.join("SKILL.md");
        if skill_file.exists() {
            let content = std::fs::read_to_string(&skill_file).unwrap_or_default();
            if !content.trim().is_empty() {
                let (manifest, body) = parse_skill_file(&content);
                let name = if !manifest.name.is_empty() {
                    manifest.name.clone()
                } else {
                    dir.file_name()
                        .map(|name| name.to_string_lossy().to_string())
                        .unwrap_or_else(|| "unknown".into())
                };
                let missing_script_refs = find_script_references(&body)
                    .into_iter()
                    .filter(|reference| !dir.join(reference).exists())
                    .collect();
                bundles.push(SkillBundleCandidate {
                    source: source.to_string(),
                    name,
                    path: dir,
                    manifest,
                    missing_script_refs,
                });
            }
            continue;
        }
        let Ok(read_dir) = std::fs::read_dir(&dir) else {
            continue;
        };
        for entry in read_dir.filter_map(|entry| entry.ok()) {
            let path = entry.path();
            if path.is_dir() {
                let name = entry.file_name().to_string_lossy().to_string();
                if !is_ignored_signal_dir(&name) {
                    stack.push(path);
                }
            }
        }
    }
    bundles.sort_by(|left, right| left.path.cmp(&right.path));
    Ok(bundles)
}

pub fn doctor_candidate_conflicts(
    candidate: &SkillBundleCandidate,
    entries: &[SkillEntry],
) -> Vec<String> {
    let candidate_entry = SkillEntry {
        name: candidate.name.clone(),
        description: candidate.manifest.description.clone(),
        id: candidate.manifest.id.clone(),
        version: candidate.manifest.version.clone(),
        tags: candidate.manifest.tags.clone(),
        aliases: candidate.manifest.aliases.clone(),
        triggers: candidate.manifest.triggers.clone(),
        activation: candidate.manifest.activation.clone(),
        profile: candidate.manifest.profile.clone(),
        project_signals: candidate.manifest.project_signals.clone(),
        posture: candidate.manifest.posture.clone(),
        max_turns: candidate.manifest.max_turns,
        installed: true,
        bundled: false,
        project_local: false,
        source: candidate.source.clone(),
        editable: false,
        reloadable: true,
        shadows: Vec::new(),
        conflicts: Vec::new(),
        path: candidate.path.display().to_string(),
    };
    entries
        .iter()
        .filter(|entry| skill_sources_conflict(&candidate_entry, entry))
        .map(|entry| skill_ref(&entry.source, &entry.name))
        .collect()
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct SkillBundleSummary {
    pub scripts: Vec<String>,
    pub resources: Vec<String>,
    pub conflicts: Vec<String>,
}

pub fn relative_file_list(root: &std::path::Path, subdir: &str) -> Vec<String> {
    let base = root.join(subdir);
    if !base.is_dir() {
        return Vec::new();
    }
    let mut stack = vec![base];
    let mut files = Vec::new();
    while let Some(dir) = stack.pop() {
        let Ok(read_dir) = std::fs::read_dir(&dir) else {
            continue;
        };
        for entry in read_dir.filter_map(|entry| entry.ok()) {
            let path = entry.path();
            let Ok(file_type) = entry.file_type() else {
                continue;
            };
            if file_type.is_dir() {
                stack.push(path);
            } else if file_type.is_file()
                && let Ok(relative) = path.strip_prefix(root)
            {
                files.push(relative.to_string_lossy().to_string());
            }
        }
    }
    files.sort();
    files
}

pub fn summarize_imported_skill(
    root: &std::path::Path,
    entry_name: &str,
    entries: &[SkillEntry],
) -> SkillBundleSummary {
    let candidate = std::fs::read_to_string(root.join("SKILL.md"))
        .ok()
        .map(|content| {
            let (manifest, _body) = parse_skill_file(&content);
            SkillBundleCandidate {
                source: "import".into(),
                name: entry_name.into(),
                path: root.to_path_buf(),
                manifest,
                missing_script_refs: Vec::new(),
            }
        });
    SkillBundleSummary {
        scripts: relative_file_list(root, "scripts"),
        resources: relative_file_list(root, "resources"),
        conflicts: candidate
            .as_ref()
            .map(|candidate| doctor_candidate_conflicts(candidate, entries))
            .unwrap_or_default(),
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SkillSignalKind {
    Literal,
    RootGlob,
    RecursiveGlob,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkillSignalMatch {
    pub signal: String,
    pub matched_path: String,
    pub kind: SkillSignalKind,
}

const IGNORED_SIGNAL_DIRS: &[&str] = &[".git", "target", "node_modules", ".venv", "dist", "build"];

/// Validate and classify a project signal from skill frontmatter.
///
/// Signals are intentionally constrained to workspace-relative literals, root
/// globs like `*.rs`, or one-recursive-segment globs like `docs/**/*.md`.
pub fn validate_project_signal(signal: &str) -> anyhow::Result<SkillSignalKind> {
    if signal.is_empty()
        || signal.starts_with('/')
        || signal.contains('\\')
        || signal.contains('\0')
        || signal
            .split('/')
            .any(|part| part.is_empty() || part == "..")
    {
        anyhow::bail!("invalid project signal '{signal}'");
    }

    if signal.contains("**") {
        if !signal.contains("**/") || signal.matches("**").count() > 1 {
            anyhow::bail!("invalid recursive project signal '{signal}'");
        }
        Ok(SkillSignalKind::RecursiveGlob)
    } else if signal.contains('*') {
        if signal.contains('/') {
            anyhow::bail!("root glob project signal must not contain '/': '{signal}'");
        }
        Ok(SkillSignalKind::RootGlob)
    } else {
        Ok(SkillSignalKind::Literal)
    }
}

/// Match a validated project signal against a workspace root.
///
/// Ignored dependency/build directories are skipped for glob searches to avoid
/// activating skills from vendor or build artifacts.
pub fn match_project_signal(
    root: &std::path::Path,
    signal: &str,
) -> anyhow::Result<Option<SkillSignalMatch>> {
    let kind = validate_project_signal(signal)?;
    let matched = match kind {
        SkillSignalKind::Literal => {
            let candidate = root.join(signal);
            candidate.exists().then_some(signal.to_string())
        }
        SkillSignalKind::RootGlob => std::fs::read_dir(root).ok().and_then(|entries| {
            entries.filter_map(|entry| entry.ok()).find_map(|entry| {
                let name = entry.file_name().to_string_lossy().to_string();
                (glob_component_matches(signal, &name) && !is_ignored_signal_dir(&name))
                    .then_some(name)
            })
        }),
        SkillSignalKind::RecursiveGlob => match_recursive_signal(root, signal)?,
    };

    Ok(matched.map(|matched_path| SkillSignalMatch {
        signal: signal.to_string(),
        matched_path,
        kind,
    }))
}

fn match_recursive_signal(root: &std::path::Path, signal: &str) -> anyhow::Result<Option<String>> {
    let Some((prefix, suffix)) = signal.split_once("**/") else {
        return Ok(None);
    };
    let prefix = prefix.trim_end_matches('/');
    let search_root = if prefix.is_empty() {
        root.to_path_buf()
    } else {
        if prefix.split('/').any(is_ignored_signal_dir) {
            return Ok(None);
        }
        root.join(prefix)
    };
    if !search_root.exists() {
        return Ok(None);
    }
    find_recursive_signal_match(root, &search_root, suffix)
}

fn find_recursive_signal_match(
    root: &std::path::Path,
    dir: &std::path::Path,
    suffix_pattern: &str,
) -> anyhow::Result<Option<String>> {
    let mut entries = match std::fs::read_dir(dir) {
        Ok(entries) => entries.filter_map(|entry| entry.ok()).collect::<Vec<_>>(),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(err) => return Err(err.into()),
    };
    entries.sort_by_key(|entry| entry.path());

    for entry in entries {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();
        if path.is_dir() {
            if is_ignored_signal_dir(&name) {
                continue;
            }
            if let Some(found) = find_recursive_signal_match(root, &path, suffix_pattern)? {
                return Ok(Some(found));
            }
        } else if glob_component_matches(suffix_pattern, &name)
            && let Ok(relative) = path.strip_prefix(root)
        {
            return Ok(Some(relative.to_string_lossy().replace('\\', "/")));
        }
    }
    Ok(None)
}

/// Return whether a directory name should be ignored during project-signal glob matching.
pub fn is_ignored_signal_dir(name: &str) -> bool {
    IGNORED_SIGNAL_DIRS.contains(&name)
}

fn glob_component_matches(pattern: &str, value: &str) -> bool {
    if pattern == "*" {
        return true;
    }
    let Some((prefix, suffix)) = pattern.split_once('*') else {
        return pattern == value;
    };
    value.starts_with(prefix) && value.ends_with(suffix)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn manifest_to_skill_file_renders_yaml_frontmatter() {
        let manifest = SkillManifest {
            name: "test".into(),
            description: "Test skill".into(),
            ..Default::default()
        };
        let file = manifest.to_skill_file("# My Skill\n\nDo things.\n");
        assert!(file.starts_with("---"));
        assert!(file.contains("name: test"));
        assert!(file.contains("# My Skill"));
    }

    #[test]
    fn parse_skill_file_yaml() {
        let content = "---\nname: test\ndescription: A test\nactivation: project_detected\nprofile: [coding]\nproject_signals: [Cargo.toml]\n---\n\n# Body\n";
        let (manifest, body) = parse_skill_file(content);
        assert_eq!(manifest.name, "test");
        assert_eq!(manifest.description, "A test");
        assert_eq!(manifest.activation, Some("project_detected".into()));
        assert_eq!(manifest.profile, vec!["coding"]);
        assert_eq!(manifest.project_signals, vec!["Cargo.toml"]);
        assert!(body.contains("# Body"));
    }

    #[test]
    fn parse_skill_file_toml() {
        let content = "+++\nname = \"test\"\ndescription = \"A test\"\nversion = \"1.0.0\"\nactivation = \"project_detected\"\nprofile = [\"coding\"]\nproject_signals = [\"Cargo.toml\"]\n+++\n\n# Body\n\nDo things.\n";
        let (manifest, body) = parse_skill_file(content);
        assert_eq!(manifest.name, "test");
        assert_eq!(manifest.description, "A test");
        assert_eq!(manifest.version, Some("1.0.0".into()));
        assert_eq!(manifest.activation, Some("project_detected".into()));
        assert_eq!(manifest.profile, vec!["coding"]);
        assert_eq!(manifest.project_signals, vec!["Cargo.toml"]);
        assert!(body.contains("# Body"));
    }

    #[test]
    fn parse_skill_file_no_frontmatter() {
        let content = "# Just markdown\n\nNo frontmatter here.\n";
        let (manifest, body) = parse_skill_file(content);
        assert_eq!(manifest.name, "");
        assert!(body.contains("Just markdown"));
    }

    #[test]
    fn split_frontmatter_detects_toml_yaml_and_absence() {
        let (fm, body) = split_frontmatter("+++\nname = \"test\"\n+++\n\nBody here.\n");
        assert!(fm.is_some());
        let (format, text) = fm.unwrap();
        assert_eq!(format, FrontmatterFormat::Toml);
        assert!(text.contains("name = \"test\""));
        assert!(body.contains("Body here."));

        let (fm, body) = split_frontmatter("---\nname: test\n---\n\nBody here.\n");
        assert!(fm.is_some());
        let (format, text) = fm.unwrap();
        assert_eq!(format, FrontmatterFormat::Yaml);
        assert!(text.contains("name: test"));
        assert!(body.contains("Body here."));

        let content = "No delimiters here.\n";
        let (fm, body) = split_frontmatter(content);
        assert!(fm.is_none());
        assert_eq!(body, content);
    }

    #[test]
    fn activation_metadata_diagnostics_cover_invalid_and_unsafe_shapes() {
        let invalid = SkillManifest {
            name: "custom".into(),
            description: "Custom skill".into(),
            activation: Some("projectish".into()),
            profile: vec!["codign".into()],
            ..Default::default()
        };
        let diagnostics = validate_activation_metadata(&invalid);
        assert!(diagnostics.activation.is_none());
        assert!(
            diagnostics
                .warnings
                .iter()
                .any(|w| w.contains("unknown activation 'projectish'"))
        );
        assert!(
            diagnostics
                .warnings
                .iter()
                .any(|w| w.contains("unknown profile 'codign'"))
        );

        let project_without_signals = SkillManifest {
            name: "custom".into(),
            description: "Custom skill".into(),
            activation: Some("project_detected".into()),
            profile: vec!["coding".into()],
            ..Default::default()
        };
        let diagnostics = validate_activation_metadata(&project_without_signals);
        assert_eq!(
            diagnostics.activation,
            Some(SkillActivation::ProjectDetected)
        );
        assert!(diagnostics.profiles.contains(&SkillProfile::Coding));
        assert!(
            diagnostics
                .warnings
                .iter()
                .any(|w| w.contains("no project_signals"))
        );

        let global_always = SkillManifest {
            name: "custom".into(),
            description: "Custom skill".into(),
            activation: Some("always".into()),
            ..Default::default()
        };
        let diagnostics = validate_activation_metadata(&global_always);
        assert_eq!(diagnostics.activation, Some(SkillActivation::Always));
        assert!(
            diagnostics
                .warnings
                .iter()
                .any(|w| w.contains("profile-scoped"))
        );
    }

    #[test]
    fn project_signal_matching_supports_literals_root_globs_and_recursive_globs() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::write(root.join("Cargo.toml"), "").unwrap();
        std::fs::write(root.join("main.rs"), "").unwrap();
        std::fs::create_dir_all(root.join("docs/nested")).unwrap();
        std::fs::write(root.join("docs/nested/guide.md"), "").unwrap();
        std::fs::create_dir_all(root.join("target/generated")).unwrap();
        std::fs::write(root.join("target/generated/ignored.md"), "").unwrap();

        let cargo = match_project_signal(root, "Cargo.toml").unwrap().unwrap();
        assert_eq!(cargo.kind, SkillSignalKind::Literal);
        assert_eq!(cargo.matched_path, "Cargo.toml");

        let rust = match_project_signal(root, "*.rs").unwrap().unwrap();
        assert_eq!(rust.kind, SkillSignalKind::RootGlob);
        assert_eq!(rust.matched_path, "main.rs");

        let docs = match_project_signal(root, "docs/**/*.md").unwrap().unwrap();
        assert_eq!(docs.kind, SkillSignalKind::RecursiveGlob);
        assert_eq!(docs.matched_path, "docs/nested/guide.md");

        assert!(
            match_project_signal(root, "target/**/*.md")
                .unwrap()
                .is_none()
        );
    }

    #[test]
    fn project_signal_validation_rejects_traversal_and_broad_recursive_shapes() {
        for signal in [
            "",
            "/tmp/file",
            "../Cargo.toml",
            "foo/../bar",
            "foo//bar",
            "foo\\bar",
            "**",
            "foo/**/bar/**/baz",
        ] {
            assert!(
                validate_project_signal(signal).is_err(),
                "{signal} should be rejected"
            );
        }
    }

    #[test]
    fn adapted_skill_warnings_cover_provenance_and_executable_posture() {
        assert!(adapted_skill_warnings("# Normal Skill\n\nNo upstream provenance.").is_empty());

        let missing = adapted_skill_warnings("## Provenance\nSource: upstream\n");
        assert!(
            missing.iter().any(|w| w.contains("## Adaptation Notes")),
            "{missing:?}"
        );
        assert!(
            missing.iter().any(|w| w.contains("## Safety Notes")),
            "{missing:?}"
        );

        let clean_missing = adapted_skill_warnings(
            "## Provenance\nKind: clean-room adaptation\n## Adaptation Notes\nNotes\n## Safety Notes\nSafe\n",
        );
        assert!(
            clean_missing
                .iter()
                .any(|w| w.contains("## Omitted Upstream Assets")),
            "{clean_missing:?}"
        );
        assert!(
            clean_missing
                .iter()
                .any(|w| w.contains("## Clean-room Rewrite Notes")),
            "{clean_missing:?}"
        );

        let executable_missing = adapted_skill_warnings("Run npm install from package.json");
        assert!(
            executable_missing
                .iter()
                .any(|w| w.contains("without explicit adaptation trust posture")),
            "{executable_missing:?}"
        );

        let complete_clean = adapted_skill_warnings(
            "## Provenance\nKind: clean-room adaptation\n## Adaptation Notes\nNotes\n## Safety Notes\nSafe\n## Omitted Upstream Assets\n- package.json\n## Clean-room Rewrite Notes\nRewritten without npm.\n",
        );
        assert!(complete_clean.is_empty(), "{complete_clean:?}");

        let trusted = adapted_skill_warnings(
            "## Provenance\nKind: trusted executable import\n## Adaptation Notes\nNotes\n## Safety Notes\nOperator trusts package.json.\nRun npm install.\n",
        );
        assert!(trusted.is_empty(), "{trusted:?}");
    }
    #[test]
    fn script_reference_discovery_is_bundle_relative_only() {
        let refs = find_script_references(
            "Use scripts/local.py, `scripts/again.sh`, ../scripts/escape.py and docs/scripts/not-local.py.",
        );
        assert_eq!(refs, vec!["scripts/local.py", "scripts/again.sh"]);
    }

    #[test]
    fn bundle_discovery_reports_missing_script_refs_and_ignores_vendor_dirs() {
        let dir = tempfile::tempdir().unwrap();
        let skill_dir = dir.path().join("skill-a");
        std::fs::create_dir_all(&skill_dir).unwrap();
        std::fs::write(
            skill_dir.join("SKILL.md"),
            "---\nname: skill-a\ndescription: Skill A\n---\n\nUse scripts/missing.py\n",
        )
        .unwrap();
        std::fs::create_dir_all(dir.path().join("node_modules/ignored-skill")).unwrap();
        std::fs::write(
            dir.path().join("node_modules/ignored-skill/SKILL.md"),
            "---\nname: ignored\ndescription: Ignored\n---\n\nBody\n",
        )
        .unwrap();

        let bundles = discover_skill_bundles("test", dir.path()).unwrap();
        assert_eq!(bundles.len(), 1);
        assert_eq!(bundles[0].name, "skill-a");
        assert_eq!(bundles[0].missing_script_refs, vec!["scripts/missing.py"]);
    }

    #[test]
    fn imported_skill_summary_lists_resources_and_conflicts() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::create_dir_all(root.join("scripts/nested")).unwrap();
        std::fs::create_dir_all(root.join("resources/templates")).unwrap();
        std::fs::write(
            root.join("SKILL.md"),
            "---\nname: rust-helper\ndescription: Rust helper\ntriggers: [rust]\n---\n\nBody\n",
        )
        .unwrap();
        std::fs::write(root.join("scripts/run.sh"), "echo run\n").unwrap();
        std::fs::write(root.join("scripts/nested/check.py"), "print('ok')\n").unwrap();
        std::fs::write(root.join("resources/templates/readme.md"), "template\n").unwrap();
        let existing = vec![SkillEntry {
            name: "other-rust".into(),
            description: String::new(),
            id: None,
            version: None,
            tags: Vec::new(),
            aliases: Vec::new(),
            triggers: vec!["rust".into()],
            activation: None,
            profile: Vec::new(),
            project_signals: Vec::new(),
            posture: None,
            max_turns: None,
            installed: true,
            bundled: false,
            project_local: false,
            source: "user".into(),
            editable: true,
            reloadable: true,
            shadows: Vec::new(),
            conflicts: Vec::new(),
            path: String::new(),
        }];

        let summary = summarize_imported_skill(root, "rust-helper", &existing);
        assert_eq!(
            summary.scripts,
            vec![
                "scripts/nested/check.py".to_string(),
                "scripts/run.sh".to_string(),
            ]
        );
        assert_eq!(
            summary.resources,
            vec!["resources/templates/readme.md".to_string()]
        );
        assert_eq!(summary.conflicts, vec!["user/other-rust".to_string()]);
    }
    #[test]
    fn trusted_paths_extract_yaml_toml_inline_and_dedupe() {
        let yaml = "---
trusted_paths:
  - ~/Documents/a
  - '~/Documents/b'
---
Body";
        assert_eq!(
            extract_trusted_paths(yaml),
            vec!["~/Documents/a".to_string(), "~/Documents/b".to_string()]
        );

        let toml = "+++
trusted_paths = [\"~/Documents/b\", \"~/Documents/a\"]
+++
Body";
        assert_eq!(
            extract_trusted_paths(toml),
            vec!["~/Documents/a".to_string(), "~/Documents/b".to_string()]
        );

        let inline = "---
trusted_paths: [~/Documents/a, \"~/Documents/a\", ~/Documents/c]
---
Body";
        assert_eq!(
            extract_trusted_paths(inline),
            vec!["~/Documents/a".to_string(), "~/Documents/c".to_string()]
        );
        assert!(extract_trusted_paths("No frontmatter").is_empty());
    }

    #[test]
    fn collect_trusted_paths_deduplicates_across_skills() {
        let skills = vec![
            "---\ntrusted_paths: [~/a, ~/b]\n---\nBody".to_string(),
            "+++\ntrusted_paths = [\"~/b\", \"~/c\"]\n+++\nBody".to_string(),
        ];
        assert_eq!(
            collect_trusted_paths(&skills),
            vec!["~/a".to_string(), "~/b".to_string(), "~/c".to_string()]
        );
    }

    #[test]
    fn phase_info_extracts_numbered_and_fractional_workflows() {
        let content = "## Phase 0.5: Prep\n\n## Phase 1: Run\n\n### Step 2: Finish\n";
        let info = extract_phase_info(content).unwrap();
        assert_eq!(info.total_phases, 3);
        assert_eq!(info.final_phase_number, "2");
        assert_eq!(info.final_phase_label, "Step 2: Finish");
        assert!(extract_phase_info("## Overview\nNo phases").is_none());
    }
    fn parsed_skill(
        name: &str,
        activation: Option<&str>,
        profile: &[&str],
        project_signals: &[&str],
        aliases: &[&str],
        triggers: &[&str],
        source: SkillSource,
    ) -> ParsedSkill {
        ParsedSkill {
            name: name.into(),
            manifest: SkillManifest {
                name: name.into(),
                description: format!("{name} skill"),
                activation: activation.map(str::to_string),
                profile: profile.iter().map(|value| value.to_string()).collect(),
                project_signals: project_signals
                    .iter()
                    .map(|value| value.to_string())
                    .collect(),
                aliases: aliases.iter().map(|value| value.to_string()).collect(),
                triggers: triggers.iter().map(|value| value.to_string()).collect(),
                ..Default::default()
            },
            source,
            path: None,
        }
    }

    #[test]
    fn skill_suggestions_are_source_agnostic_for_coding_projects() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::write(root.join("Cargo.toml"), "[package]\n").unwrap();
        let skills = vec![
            parsed_skill(
                "rust",
                Some("project_detected"),
                &["coding"],
                &["Cargo.toml"],
                &[],
                &[],
                SkillSource::Bundled,
            ),
            parsed_skill(
                "git",
                Some("always"),
                &["coding"],
                &[],
                &[],
                &[],
                SkillSource::Bundled,
            ),
            parsed_skill(
                "security",
                Some("always"),
                &["coding"],
                &[],
                &[],
                &[],
                SkillSource::Bundled,
            ),
        ];

        let suggestions = suggest_skills_for_context(
            &skills,
            SkillSuggestionContext {
                root,
                profiles: &[SkillProfile::Coding],
                intent_terms: &[],
            },
        );
        let names: Vec<&str> = suggestions
            .iter()
            .map(|suggestion| suggestion.name.as_str())
            .collect();
        assert!(names.contains(&"rust"), "suggestions: {names:?}");
        assert!(names.contains(&"git"), "suggestions: {names:?}");
        assert!(names.contains(&"security"), "suggestions: {names:?}");
    }

    #[test]
    fn skill_suggestions_gate_domain_and_lifecycle_skills() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::write(root.join("README.md"), "# docs\n").unwrap();
        std::fs::create_dir_all(root.join("openspec/changes/demo")).unwrap();
        let skills = vec![
            parsed_skill(
                "flynt",
                Some("domain_detected"),
                &["docs"],
                &["README.md"],
                &[],
                &[],
                SkillSource::Bundled,
            ),
            parsed_skill(
                "openspec",
                Some("lifecycle_gated"),
                &["lifecycle"],
                &["openspec/changes"],
                &[],
                &[],
                SkillSource::Bundled,
            ),
        ];

        let coding = suggest_skills_for_context(
            &skills,
            SkillSuggestionContext {
                root,
                profiles: &[SkillProfile::Coding],
                intent_terms: &[],
            },
        );
        assert!(coding.is_empty(), "coding suggestions: {coding:?}");

        let docs = suggest_skills_for_context(
            &skills,
            SkillSuggestionContext {
                root,
                profiles: &[SkillProfile::Docs],
                intent_terms: &[],
            },
        );
        assert!(docs.iter().any(|suggestion| suggestion.name == "flynt"));
        assert!(!docs.iter().any(|suggestion| suggestion.name == "openspec"));

        let lifecycle = suggest_skills_for_context(
            &skills,
            SkillSuggestionContext {
                root,
                profiles: &[SkillProfile::Lifecycle],
                intent_terms: &[],
            },
        );
        assert!(
            lifecycle
                .iter()
                .any(|suggestion| suggestion.name == "openspec")
        );
    }

    #[test]
    fn skill_suggestions_use_intent_and_preserve_external_warnings() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let legacy = parsed_skill(
            "legacy-batch",
            None,
            &[],
            &[],
            &["batch"],
            &[],
            SkillSource::UserInstalled,
        );
        let unknown = parsed_skill(
            "odd",
            Some("projectish"),
            &["codign"],
            &["../bad"],
            &["odd"],
            &[],
            SkillSource::ProjectLocal,
        );
        let code_act = parsed_skill(
            "code-act",
            Some("intent_detected"),
            &["coding"],
            &[],
            &["script"],
            &["write a script"],
            SkillSource::Bundled,
        );
        let skills = vec![legacy, unknown, code_act];

        let suggestions = suggest_skills_for_context(
            &skills,
            SkillSuggestionContext {
                root,
                profiles: &[SkillProfile::Coding],
                intent_terms: &["batch", "odd", "script"],
            },
        );
        let legacy = suggestions
            .iter()
            .find(|suggestion| suggestion.name == "legacy-batch")
            .expect("legacy skill should be suggested by explicit intent");
        assert_eq!(legacy.source, SkillSource::UserInstalled);
        assert!(
            legacy
                .warnings
                .iter()
                .any(|warning| warning.contains("unspecified"))
        );
        assert!(
            suggestions
                .iter()
                .any(|suggestion| suggestion.name == "code-act")
        );
        let odd = suggestions
            .iter()
            .find(|suggestion| suggestion.name == "odd")
            .expect("unknown metadata skill should remain visible by explicit intent");
        assert_eq!(odd.source, SkillSource::ProjectLocal);
        assert!(
            odd.warnings
                .iter()
                .any(|warning| warning.contains("unknown activation"))
        );
        assert!(
            odd.warnings
                .iter()
                .any(|warning| warning.contains("unknown profile"))
        );
        assert!(
            odd.warnings
                .iter()
                .any(|warning| warning.contains("invalid project_signal"))
        );
    }
}
