#!/usr/bin/env python3
"""Generate or check the canonical shipped content-pack manifest."""

from __future__ import annotations

import argparse
import hashlib
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "content-pack.toml"
KINDS = {
    "skills": ("skill", "content:skill-metadata"),
    "prompts": ("prompt", "content:prompt-template"),
    "personas": ("persona", "content:persona-directive"),
    "tones": ("tone", "content:tone-directive"),
    "workflows": ("workflow", "content:workflow-template"),
    "catalog": ("catalog", "content:catalog-data"),
}
CAPABILITIES = sorted(capability for _, capability in KINDS.values())
DOMAIN = b"omegon-content-pack-v1\0"


def assets() -> list[dict[str, object]]:
    result: list[dict[str, object]] = []
    for directory, (kind, capability) in KINDS.items():
        root = ROOT / directory
        if not root.is_dir():
            continue
        for path in sorted(path for path in root.rglob("*") if path.is_file()):
            relative = path.relative_to(ROOT).as_posix()
            payload = path.read_bytes()
            result.append({
                "path": relative,
                "kind": kind,
                "sha256": hashlib.sha256(payload).hexdigest(),
                "size": len(payload),
                "capability": capability,
            })
    return sorted(result, key=lambda asset: str(asset["path"]))


def canonical_digest(inventory: list[dict[str, object]]) -> str:
    digest = hashlib.sha256(DOMAIN)
    for asset in inventory:
        path = str(asset["path"]).encode()
        digest.update(len(path).to_bytes(8, "big"))
        digest.update(path)
        digest.update(int(asset["size"]).to_bytes(8, "big"))
        digest.update(bytes.fromhex(str(asset["sha256"])))
    return digest.hexdigest()


def render() -> str:
    inventory = assets()
    lines = [
        "# Generated by scripts/content_pack_manifest.py; do not edit by hand.",
        "schema_version = 1",
        'id = "omegon-shipped"',
        'version = "1.0.0"',
        f'canonical_digest = "{canonical_digest(inventory)}"',
        "requested_capabilities = [",
    ]
    lines.extend(f'  "{capability}",' for capability in CAPABILITIES)
    lines.extend([
        "]",
        "",
        "[provenance]",
        'publisher = "Styrene Lab"',
        'source = "https://github.com/styrene-lab/omegon"',
        'revision = "omegon-shipped-content-v1"',
        "",
        "[compatibility]",
        "content_protocol_min = 1",
        "content_protocol_max = 1",
    ])
    for asset in inventory:
        lines.extend([
            "",
            "[[assets]]",
            f'path = "{asset["path"]}"',
            f'kind = "{asset["kind"]}"',
            f'sha256 = "{asset["sha256"]}"',
            f'size = {asset["size"]}',
            f'requested_capabilities = ["{asset["capability"]}"]',
        ])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--install-root", type=Path)
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not MANIFEST.exists() or MANIFEST.read_text() != expected:
            raise SystemExit("content-pack manifest is stale; run scripts/content_pack_manifest.py")
        return 0
    if args.install_root is not None:
        destination = args.install_root
        if destination.exists():
            shutil.rmtree(destination)
        destination.mkdir(parents=True)
        (destination / MANIFEST.name).write_text(expected)
        for asset in assets():
            source = ROOT / str(asset["path"])
            target = destination / str(asset["path"])
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, target)
        return 0
    MANIFEST.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
