#!/usr/bin/env node
/**
 * Generate themes/alpharius.conf (Kitty terminal theme) from themes/alpharius.json.
 *
 * Goal: make Kitty's chrome *compatible* with the Alpharius palette — not a
 * perfect mirror.  Pi renders everything in 24-bit RGB, so the ANSI 16-colour
 * slots only affect things outside pi (shell prompt, ls, git diff, etc.).
 * We set the minimum needed to avoid visual seams:
 *
 *   1. background/foreground/cursor — must match so pi's rendering regions
 *      blend seamlessly into the naked terminal.
 *   2. selection + url — should feel on-palette.
 *   3. Tab bar / window borders — Kitty chrome that pi can't control.
 *   4. ANSI colours (0-15) — reasonable defaults that won't clash; we use
 *      the alpharius signal colours where they map cleanly (red/green/yellow)
 *      and leave the rest as sensible dark-theme values.
 *
 * Run after any background/foreground/cursor/border palette change:
 *   npx tsx scripts/export-kitty-theme.ts
 *
 * Install:
 *   cp themes/alpharius.conf ~/.config/kitty/themes/alpharius.conf
 *   # then in kitty.conf: include themes/alpharius.conf
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const theme = JSON.parse(
  readFileSync(resolve(root, "themes/alpharius.json"), "utf8"),
) as { vars: Record<string, string> };

const v = theme.vars;

// ── Build conf ───────────────────────────────────────────────────────────────

const lines: string[] = [
  `# Alpharius — Kitty compatibility layer`,
  `# Generated by scripts/export-kitty-theme.ts — do not edit manually.`,
  `#`,
  `# This file makes Kitty's chrome compatible with the Alpharius palette.`,
  `# Pi renders in 24-bit RGB so the ANSI palette is not a full mirror —`,
  `# only background/foreground/cursor need to match exactly.`,
  `#`,
  `# Install:`,
  `#   cp themes/alpharius.conf ~/.config/kitty/themes/alpharius.conf`,
  `#   then in kitty.conf: include themes/alpharius.conf`,
  ``,
  `# ── Seamless background/foreground (must match pi exactly) ───────────────`,
  `background            ${v.bg}`,
  `foreground            ${v.fg}`,
  ``,
  `# ── Cursor ───────────────────────────────────────────────────────────────`,
  `cursor                ${v.primary}`,
  `cursor_text_color     ${v.bg}`,
  ``,
  `# ── Selection ────────────────────────────────────────────────────────────`,
  `selection_background  ${v.selectedBg}`,
  `selection_foreground  ${v.fg}`,
  ``,
  `# ── URL underline ────────────────────────────────────────────────────────`,
  `url_color             ${v.primaryMuted}`,
  ``,
  `# ── Tab bar ──────────────────────────────────────────────────────────────`,
  `active_tab_foreground   ${v.fg}`,
  `active_tab_background   ${v.cardBg}`,
  `inactive_tab_foreground ${v.mutedFg}`,
  `inactive_tab_background ${v.bg}`,
  `tab_bar_background      ${v.bg}`,
  ``,
  `# ── Window borders ───────────────────────────────────────────────────────`,
  `active_border_color     ${v.primary}`,
  `inactive_border_color   ${v.borderColor}`,
  `bell_border_color       ${v.orange}`,
  ``,
  `# ── ANSI 16-colour palette ───────────────────────────────────────────────`,
  `# Used only by things outside pi (shell prompt, ls, git diff).`,
  `# Signal colours (red/green/yellow) use alpharius values for consistency.`,
  `# The rest are reasonable dark-theme defaults that won't clash.`,
  `color0   ${v.bg}`,          // black       — void background
  `color1   ${v.red}`,         // red         — errors
  `color2   ${v.green}`,       // green       — success
  `color3   ${v.yellow}`,      // yellow      — warnings
  `color4   ${v.primaryMuted}`,// blue        — links / secondary accent
  `color5   #6060c0`,          // magenta     — no alpharius equivalent; neutral purple
  `color6   ${v.syntaxType}`,  // cyan        — teal variant
  `color7   ${v.mutedFg}`,     // white       — muted text
  `color8   ${v.dimFg}`,       // bright-black — dim / comments
  `color9   #e04040`,          // bright-red   — lighter error
  `color10  #30e898`,          // bright-green — lighter success
  `color11  #a0d030`,          // bright-yellow — lighter warning
  `color12  ${v.primary}`,     // bright-blue  — primary accent
  `color13  #8080d0`,          // bright-magenta
  `color14  ${v.primaryBright}`,// bright-cyan — silver-teal
  `color15  ${v.fg}`,          // bright-white — full foreground
  ``,
];

const output = lines.join("\n") + "\n";
const outPath = resolve(root, "themes/alpharius.conf");
writeFileSync(outPath, output, "utf8");
console.log(`Written: themes/alpharius.conf`);
