//! Skill management — schema, parsing, listing, and installation.
//!
//! Skills are markdown directive files injected into the system prompt at session start.
//! Bundled skills ship embedded in the binary so `omegon skills install` works regardless
//! of whether a source tree is present.
//!
//! Two-tier load order (established by PluginRegistry::load_skills):
//!   1. ~/.omegon/skills/*/SKILL.md   — bundled / user-installed
//!   2. <cwd>/.omegon/skills/*/SKILL.md — project-local (overrides bundled)
//!
//! ## Skill Schema
//!
//! SKILL.md files use TOML (`+++`) or YAML (`---`) frontmatter with these fields:
//!
//! ```toml
//! +++
//! # ── Required ─────────────────────────────────────────
//! name = "my-skill"
//! description = "What this skill does"
//!
//! # ── Identity (auto-generated) ────────────────────────
//! id = "uuid"                          # unique identifier
//! version = "1.0.0"                    # skill version
//! tags = ["domain", "category"]        # discovery/filtering
//! aliases = ["shortname"]              # alternative invocation names
//!
//! # ── Invocation ───────────────────────────────────────
//! triggers = [                         # phrases that activate this skill
//!   "evaluate this opportunity",
//!   "assess this solicitation",
//! ]
//!
//! # ── Access ───────────────────────────────────────────
//! trusted_paths = [                    # auto-trusted on load
//!   "~/Documents/data/",
//! ]
//!
//! # ── Output ───────────────────────────────────────────
//! output_path = "~/Documents/output/"  # where results are written
//! output_format = "markdown"           # markdown | json
//!
//! # ── Constraints ──────────────────────────────────────
//! max_turns = 100                      # override session default
//! posture = "architect"                # recommended posture
//! +++
//! ```
//!
//! All fields except `name` and `description` are optional.
//! The markdown body after the frontmatter is the skill's directive content.

/// Parsed skill manifest — the structured metadata from SKILL.md frontmatter.
///
/// All fields except `name` and `description` are optional. This struct is
/// used by the skill builder, the TUI `/skills` command, and the setup
/// pipeline for trusted_paths and phase tracking.
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct SkillManifest {
    /// Kebab-case unique name (e.g., "opportunity-eval").
    pub name: String,
    /// One-line description shown in `/skills list`.
    pub description: String,
    /// Unique identifier (UUID). Auto-generated by the builder.
    #[serde(default)]
    pub id: Option<String>,
    /// Skill version (e.g., "1.0.0"). For user tracking, not enforced.
    #[serde(default)]
    pub version: Option<String>,
    /// Discovery/filtering tags (e.g., ["govcon", "research"]).
    #[serde(default)]
    pub tags: Vec<String>,
    /// Alternative invocation names (e.g., ["eval", "opp"]).
    #[serde(default)]
    pub aliases: Vec<String>,
    /// Phrases that trigger this skill (e.g., "evaluate this opportunity").
    #[serde(default)]
    pub triggers: Vec<String>,
    /// Paths outside the workspace this skill needs access to.
    /// Auto-trusted on session startup and persisted to settings.
    #[serde(default)]
    pub trusted_paths: Vec<String>,
    /// Where results should be written.
    #[serde(default)]
    pub output_path: Option<String>,
    /// Output format hint: "markdown", "json", etc.
    #[serde(default)]
    pub output_format: Option<String>,
    /// Recommended max_turns override for this skill.
    #[serde(default)]
    pub max_turns: Option<u32>,
    /// Recommended posture (e.g., "architect", "fabricator").
    #[serde(default)]
    pub posture: Option<String>,
}

impl SkillManifest {
    /// Render this manifest as TOML frontmatter for a SKILL.md file.
    pub fn to_frontmatter(&self) -> String {
        let mut lines = vec!["+++".to_string()];

        if let Some(ref id) = self.id {
            lines.push(format!("id = \"{id}\""));
        }
        lines.push(format!("name = \"{}\"", self.name));
        lines.push(format!("description = \"{}\"", self.description));

        if let Some(ref version) = self.version {
            lines.push(format!("version = \"{version}\""));
        }
        if !self.tags.is_empty() {
            let tags: Vec<String> = self.tags.iter().map(|t| format!("\"{t}\"")).collect();
            lines.push(format!("tags = [{}]", tags.join(", ")));
        }
        if !self.aliases.is_empty() {
            let aliases: Vec<String> = self.aliases.iter().map(|a| format!("\"{a}\"")).collect();
            lines.push(format!("aliases = [{}]", aliases.join(", ")));
        }
        if !self.triggers.is_empty() {
            let triggers: Vec<String> = self.triggers.iter().map(|t| format!("\"{t}\"")).collect();
            lines.push(format!("triggers = [{}]", triggers.join(", ")));
        }
        if !self.trusted_paths.is_empty() {
            let paths: Vec<String> = self.trusted_paths.iter().map(|p| format!("\"{p}\"")).collect();
            lines.push(format!("trusted_paths = [{}]", paths.join(", ")));
        }
        if let Some(ref path) = self.output_path {
            lines.push(format!("output_path = \"{path}\""));
        }
        if let Some(ref fmt) = self.output_format {
            lines.push(format!("output_format = \"{fmt}\""));
        }
        if let Some(turns) = self.max_turns {
            lines.push(format!("max_turns = {turns}"));
        }
        if let Some(ref posture) = self.posture {
            lines.push(format!("posture = \"{posture}\""));
        }

        lines.push("+++".to_string());
        lines.join("\n")
    }

    /// Generate a complete SKILL.md file from this manifest and a body.
    pub fn to_skill_file(&self, body: &str) -> String {
        format!("{}\n\n{}", self.to_frontmatter(), body)
    }
}

/// Generate the system prompt for the skill builder conversation.
/// The agent uses this to guide the operator through creating a skill.
pub fn skill_builder_prompt(cwd: &std::path::Path) -> String {
    format!(
        r#"You are helping the operator create a new Omegon skill. A skill is a reusable directive that tells the agent how to handle a specific type of task.

Guide the operator through these questions conversationally. Be concise — one question at a time, don't overwhelm.

1. **What should this skill do?** Get a clear description of the task or workflow.
2. **What should it be called?** Suggest a kebab-case name based on their description. Keep it short.
3. **Does it need files outside the project?** Ask if it reads from or writes to directories outside {cwd}. If so, get the paths (e.g., ~/Documents/references/).
4. **Where should output go?** If the skill produces files, where should they be saved?
5. **Any trigger phrases?** What would the operator say to invoke this skill? (e.g., "evaluate this opportunity")

After gathering answers, generate a complete SKILL.md file using this exact TOML frontmatter schema:

```toml
+++
id = "<generate-a-uuid>"
name = "<kebab-case-name>"
description = "<one-line description>"
version = "1.0.0"
tags = ["<domain>"]
aliases = ["<shortname>"]
triggers = ["<phrase1>", "<phrase2>"]
trusted_paths = ["<path1>", "<path2>"]
output_path = "<where results go>"
output_format = "markdown"
+++
```

Only include fields that have values — omit any that are empty or not applicable.
The `id` field should be a freshly generated UUID.

The markdown body after the frontmatter should contain:
- If it's a workflow: numbered phases (## Phase 0: ..., ## Phase 1: ..., etc.)
- If it's conventions: organized sections (## Setup, ## Rules, etc.)
- Concrete, actionable instructions — not vague guidance

First create the directory, then write the file:
  mkdir -p {cwd}/.omegon/skills/<name>/
  Then write to {cwd}/.omegon/skills/<name>/SKILL.md

After writing, confirm the full path to the operator and tell them the skill will be active in their next session.

Do NOT ask all questions at once. Start with question 1 only."#,
        cwd = cwd.display()
    )
}

/// All skills bundled into the binary at compile time.
/// Each entry is (name, skill_markdown_content).
pub const BUNDLED: &[(&str, &str)] = &[
    ("git", include_str!("../../../../skills/git/SKILL.md")),
    ("oci", include_str!("../../../../skills/oci/SKILL.md")),
    (
        "openspec",
        include_str!("../../../../skills/openspec/SKILL.md"),
    ),
    ("python", include_str!("../../../../skills/python/SKILL.md")),
    ("rust", include_str!("../../../../skills/rust/SKILL.md")),
    (
        "security",
        include_str!("../../../../skills/security/SKILL.md"),
    ),
    ("style", include_str!("../../../../skills/style/SKILL.md")),
    (
        "typescript",
        include_str!("../../../../skills/typescript/SKILL.md"),
    ),
    ("vault", include_str!("../../../../skills/vault/SKILL.md")),
];

fn skills_dir() -> Option<std::path::PathBuf> {
    crate::paths::omegon_home().ok().map(|h| h.join("skills"))
}

/// Render bundled skills and their installation status as terminal-friendly text.
pub fn list_summary() -> anyhow::Result<String> {
    let skills_dir = skills_dir();

    let mut lines = vec![format!("Bundled skills ({})\n", BUNDLED.len())];

    for (name, content) in BUNDLED {
        // Extract description from frontmatter if present
        let description = extract_description(content).unwrap_or("(no description)");

        let installed = skills_dir
            .as_ref()
            .is_some_and(|d| d.join(name).join("SKILL.md").exists());
        let status = if installed { "✓" } else { "○" };
        lines.push(format!("  {status} {name:<14} {description}"));
    }

    let install_path = skills_dir
        .as_ref()
        .map(|d| d.display().to_string())
        .unwrap_or_else(|| "(unknown)".into());

    lines.push(format!("\nInstall location: {install_path}"));
    lines.push("  ✓ = installed    ○ = not yet installed".into());
    lines.push("\nRun `omegon skills install` to install all bundled skills.".into());

    // Show any project-local skills if cwd has them
    let cwd = std::env::current_dir()?;
    let project_skills = cwd.join(".omegon").join("skills");
    if project_skills.is_dir() {
        let mut local: Vec<String> = std::fs::read_dir(&project_skills)?
            .filter_map(|e| e.ok())
            .filter(|e| e.path().join("SKILL.md").exists())
            .map(|e| e.file_name().to_string_lossy().to_string())
            .collect();
        local.sort();
        if !local.is_empty() {
            lines.push("\nProject-local skills (.omegon/skills/):".into());
            for name in &local {
                lines.push(format!("  ● {name}"));
            }
        }
    }

    Ok(lines.join("\n"))
}

/// List bundled skills and their installation status.
pub fn cmd_list() -> anyhow::Result<()> {
    println!("{}", list_summary()?);
    Ok(())
}

/// Install all bundled skills to ~/.omegon/skills/.
/// Existing files are overwritten. Project-local skills are never touched.
pub fn cmd_install() -> anyhow::Result<()> {
    let skills_dir =
        skills_dir().ok_or_else(|| anyhow::anyhow!("Cannot determine home directory"))?;

    std::fs::create_dir_all(&skills_dir)?;

    let mut installed = 0;
    let mut updated = 0;

    for (name, content) in BUNDLED {
        let skill_dir = skills_dir.join(name);
        let skill_file = skill_dir.join("SKILL.md");

        std::fs::create_dir_all(&skill_dir)?;

        let already_exists = skill_file.exists();
        let existing_content = if already_exists {
            std::fs::read_to_string(&skill_file).ok()
        } else {
            None
        };

        let changed = existing_content.as_deref() != Some(content);

        std::fs::write(&skill_file, content)?;

        if !already_exists {
            println!("  + {name}");
            installed += 1;
        } else if changed {
            println!("  ↑ {name}  (updated)");
            updated += 1;
        } else {
            println!("  ✓ {name}  (unchanged)");
        }
    }

    println!(
        "\n{} skill(s) installed, {} updated → {}",
        installed,
        updated,
        skills_dir.display()
    );
    println!("Skills are active immediately in new sessions.");

    Ok(())
}

/// Extract `trusted_paths` from SKILL.md frontmatter.
///
/// Skills that need to read/write outside the workspace can declare paths
/// in their frontmatter. On session startup, these paths are auto-trusted
/// (added to settings.trusted_directories if not already present), so the
/// user isn't prompted repeatedly.
///
/// YAML format:
/// ```yaml
/// trusted_paths:
///   - ~/Documents/pastperformance/
///   - ~/Library/Mobile Documents/iCloud~md~obsidian/Documents/jaredp/evaluations/
/// ```
///
/// TOML format:
/// ```toml
/// trusted_paths = ["~/Documents/pastperformance/"]
/// ```
pub fn extract_trusted_paths(content: &str) -> Vec<String> {
    let (body, delimiter) = if let Some(b) = content.strip_prefix("---\n") {
        (b, "\n---")
    } else if let Some(b) = content.strip_prefix("+++\n") {
        (b, "\n+++")
    } else {
        return Vec::new();
    };
    let end = match body.find(delimiter) {
        Some(e) => e,
        None => return Vec::new(),
    };
    let frontmatter = &body[..end];

    let mut paths = Vec::new();

    // TOML: trusted_paths = ["path1", "path2"]
    for line in frontmatter.lines() {
        if let Some(rest) = line.strip_prefix("trusted_paths") {
            let rest = rest.trim();
            if let Some(rest) = rest.strip_prefix('=') {
                let rest = rest.trim();
                if rest.starts_with('[') {
                    // Parse simple TOML array: ["path1", "path2"]
                    let inner = rest.trim_start_matches('[').trim_end_matches(']');
                    for item in inner.split(',') {
                        let item = item.trim().trim_matches('"').trim_matches('\'');
                        if !item.is_empty() {
                            paths.push(item.to_string());
                        }
                    }
                }
            }
        }
    }

    // YAML: trusted_paths:\n  - path1\n  - path2
    let mut in_trusted_paths = false;
    for line in frontmatter.lines() {
        if line.starts_with("trusted_paths:") {
            in_trusted_paths = true;
            // Check for inline value: trusted_paths: [path1, path2]
            let rest = line.strip_prefix("trusted_paths:").unwrap().trim();
            if rest.starts_with('[') {
                let inner = rest.trim_start_matches('[').trim_end_matches(']');
                for item in inner.split(',') {
                    let item = item.trim().trim_matches('"').trim_matches('\'');
                    if !item.is_empty() {
                        paths.push(item.to_string());
                    }
                }
                in_trusted_paths = false;
            }
            continue;
        }
        if in_trusted_paths {
            let trimmed = line.trim();
            if let Some(path) = trimmed.strip_prefix("- ") {
                let path = path.trim().trim_matches('"').trim_matches('\'');
                if !path.is_empty() {
                    paths.push(path.to_string());
                }
            } else if !trimmed.is_empty() && !trimmed.starts_with('#') {
                // Not a list item — end of trusted_paths block
                in_trusted_paths = false;
            }
        }
    }

    paths.sort();
    paths.dedup();
    paths
}

/// Collect trusted_paths from all loaded skill content strings.
pub fn collect_trusted_paths(skills: &[String]) -> Vec<String> {
    let mut all_paths = Vec::new();
    for content in skills {
        all_paths.extend(extract_trusted_paths(content));
    }
    all_paths.sort();
    all_paths.dedup();
    all_paths
}

/// Extract phase/step markers from skill content for completion tracking.
///
/// Looks for markdown headings that indicate numbered phases or steps:
///   `## Phase 1:`, `## Phase 2:`, ..., `## Step 1:`, `## Step 2:`, ...
///   `## Phase 0.5:`, `## Phase 1.75:` (fractional phases like in jputman's skill)
///
/// Returns the total number of phases and the label of the final phase
/// (e.g., "Phase 10: Export to File"). Used by the loop to detect
/// premature completion — if the agent declares "done" without reaching
/// the final phase, it gets nudged.
pub fn extract_phase_info(content: &str) -> Option<SkillPhaseInfo> {
    let mut phases: Vec<(String, String)> = Vec::new(); // (number, full heading)

    for line in content.lines() {
        let trimmed = line.trim();
        // Match: ## Phase N: ... or ## Step N: ...
        // Also handles ### Phase N, # Phase N, etc.
        if let Some(rest) = trimmed
            .strip_prefix('#')
            .and_then(|s| s.trim_start_matches('#').trim_start().strip_prefix("Phase "))
            .or_else(|| {
                trimmed
                    .strip_prefix('#')
                    .and_then(|s| s.trim_start_matches('#').trim_start().strip_prefix("Step "))
            })
        {
            // Extract the phase number (may be fractional: "0.5", "1.75")
            let num_end = rest
                .find(|c: char| !c.is_ascii_digit() && c != '.')
                .unwrap_or(rest.len());
            let num = &rest[..num_end];
            if !num.is_empty() {
                let heading = trimmed
                    .trim_start_matches('#')
                    .trim()
                    .to_string();
                phases.push((num.to_string(), heading));
            }
        }
    }

    if phases.is_empty() {
        return None;
    }

    let final_phase = phases.last().unwrap();
    Some(SkillPhaseInfo {
        total_phases: phases.len(),
        final_phase_label: final_phase.1.clone(),
        final_phase_number: final_phase.0.clone(),
    })
}

/// Phase tracking info extracted from a skill's content.
#[derive(Debug, Clone)]
pub struct SkillPhaseInfo {
    /// Total number of phase/step headings found.
    pub total_phases: usize,
    /// The heading text of the final phase (e.g., "Phase 10: Export to File").
    pub final_phase_label: String,
    /// The phase number string (e.g., "10", "1.75").
    pub final_phase_number: String,
}

/// Collect phase info from all loaded skills. Returns info for any skill
/// that has numbered phases (most skills don't — only structured workflows like
/// jputman's opportunity-eval).
pub fn collect_phase_info(skills: &[String]) -> Vec<SkillPhaseInfo> {
    skills.iter().filter_map(|s| extract_phase_info(s)).collect()
}

/// A skill entry with structured metadata for the ACP settings surface.
#[derive(Debug, Clone, serde::Serialize)]
pub struct SkillEntry {
    pub name: String,
    pub description: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    pub tags: Vec<String>,
    pub aliases: Vec<String>,
    pub triggers: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub posture: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_turns: Option<u32>,
    pub installed: bool,
    pub bundled: bool,
    pub project_local: bool,
    pub path: String,
}

/// Parse a SKILL.md into its manifest and body text.
pub fn parse_skill_file(content: &str) -> (SkillManifest, String) {
    let (fm_str, body) = split_frontmatter(content);
    let manifest = if let Some(fm) = fm_str {
        toml::from_str::<SkillManifest>(&fm).unwrap_or_default()
    } else {
        SkillManifest::default()
    };
    (manifest, body.to_string())
}

fn split_frontmatter(content: &str) -> (Option<String>, &str) {
    let (rest, delimiter) = if let Some(b) = content.strip_prefix("+++\n") {
        (b, "\n+++")
    } else if let Some(b) = content.strip_prefix("---\n") {
        (b, "\n---")
    } else {
        return (None, content);
    };
    match rest.find(delimiter) {
        Some(end) => {
            let fm = &rest[..end];
            let body = &rest[end + delimiter.len()..];
            let body = body.strip_prefix('\n').unwrap_or(body);
            (Some(fm.to_string()), body)
        }
        None => (None, content),
    }
}

/// List all skills as structured entries for the ACP settings surface.
///
/// Returns bundled skills (with installation status), user-installed skills,
/// and project-local skills in a single sorted list.
pub fn list_structured() -> anyhow::Result<Vec<SkillEntry>> {
    let home_skills = skills_dir();
    let cwd = std::env::current_dir()?;
    let project_skills = cwd.join(".omegon").join("skills");
    let mut entries = Vec::new();
    let mut seen = std::collections::HashSet::new();

    // Bundled skills — always present, may or may not be installed
    for (name, content) in BUNDLED {
        let (manifest, _body) = parse_skill_file(content);
        let installed = home_skills
            .as_ref()
            .is_some_and(|d| d.join(name).join("SKILL.md").exists());
        let path = home_skills
            .as_ref()
            .map(|d| d.join(name).display().to_string())
            .unwrap_or_default();
        entries.push(SkillEntry {
            name: name.to_string(),
            description: manifest.description.clone(),
            id: manifest.id.clone(),
            version: manifest.version.clone(),
            tags: manifest.tags.clone(),
            aliases: manifest.aliases.clone(),
            triggers: manifest.triggers.clone(),
            posture: manifest.posture.clone(),
            max_turns: manifest.max_turns,
            installed,
            bundled: true,
            project_local: false,
            path,
        });
        seen.insert(name.to_string());
    }

    // User-installed skills (non-bundled)
    if let Some(ref dir) = home_skills {
        if dir.is_dir() {
            let mut user_skills: Vec<_> = std::fs::read_dir(dir)?
                .filter_map(|e| e.ok())
                .filter(|e| e.path().join("SKILL.md").exists())
                .map(|e| e.file_name().to_string_lossy().to_string())
                .filter(|name| !seen.contains(name))
                .collect();
            user_skills.sort();
            for name in user_skills {
                let skill_path = dir.join(&name).join("SKILL.md");
                let content = std::fs::read_to_string(&skill_path).unwrap_or_default();
                let (manifest, _body) = parse_skill_file(&content);
                entries.push(SkillEntry {
                    name: name.clone(),
                    description: manifest.description.clone(),
                    id: manifest.id.clone(),
                    version: manifest.version.clone(),
                    tags: manifest.tags.clone(),
                    aliases: manifest.aliases.clone(),
                    triggers: manifest.triggers.clone(),
                    posture: manifest.posture.clone(),
                    max_turns: manifest.max_turns,
                    installed: true,
                    bundled: false,
                    project_local: false,
                    path: dir.join(&name).display().to_string(),
                });
                seen.insert(name);
            }
        }
    }

    // Project-local skills
    if project_skills.is_dir() {
        let mut local: Vec<_> = std::fs::read_dir(&project_skills)?
            .filter_map(|e| e.ok())
            .filter(|e| e.path().join("SKILL.md").exists())
            .map(|e| e.file_name().to_string_lossy().to_string())
            .collect();
        local.sort();
        for name in local {
            let skill_path = project_skills.join(&name).join("SKILL.md");
            let content = std::fs::read_to_string(&skill_path).unwrap_or_default();
            let (manifest, _body) = parse_skill_file(&content);
            let already_seen = seen.contains(&name);
            if !already_seen {
                entries.push(SkillEntry {
                    name: name.clone(),
                    description: manifest.description.clone(),
                    id: manifest.id.clone(),
                    version: manifest.version.clone(),
                    tags: manifest.tags.clone(),
                    aliases: manifest.aliases.clone(),
                    triggers: manifest.triggers.clone(),
                    posture: manifest.posture.clone(),
                    max_turns: manifest.max_turns,
                    installed: true,
                    bundled: false,
                    project_local: true,
                    path: project_skills.join(&name).display().to_string(),
                });
            }
        }
    }

    Ok(entries)
}

/// Read a single skill's manifest and body content.
pub fn get_skill(name: &str) -> anyhow::Result<(SkillManifest, String, std::path::PathBuf)> {
    if name.contains('/') || name.contains('\\') || name.contains("..") || name.contains('\0') {
        anyhow::bail!("invalid skill name: path traversal rejected");
    }

    // Project-local takes precedence
    let cwd = std::env::current_dir()?;
    let project_path = cwd.join(".omegon/skills").join(name).join("SKILL.md");
    if project_path.exists() {
        let content = std::fs::read_to_string(&project_path)?;
        let (manifest, body) = parse_skill_file(&content);
        return Ok((manifest, body, project_path.parent().unwrap().to_path_buf()));
    }

    // User-installed / bundled
    if let Some(dir) = skills_dir() {
        let skill_path = dir.join(name).join("SKILL.md");
        if skill_path.exists() {
            let content = std::fs::read_to_string(&skill_path)?;
            let (manifest, body) = parse_skill_file(&content);
            return Ok((manifest, body, skill_path.parent().unwrap().to_path_buf()));
        }
    }

    // Check if it's a known bundled skill (not yet installed)
    for (bname, content) in BUNDLED {
        if *bname == name {
            let (manifest, body) = parse_skill_file(content);
            let path = skills_dir()
                .map(|d| d.join(name))
                .unwrap_or_default();
            return Ok((manifest, body, path));
        }
    }

    anyhow::bail!("skill '{name}' not found")
}

/// Extract the `description` field from YAML frontmatter.
fn extract_description(content: &str) -> Option<&str> {
    // Support both YAML (---) and TOML (+++) frontmatter delimiters.
    let (body, delimiter) = if let Some(b) = content.strip_prefix("---\n") {
        (b, "\n---")
    } else if let Some(b) = content.strip_prefix("+++\n") {
        (b, "\n+++")
    } else {
        return None;
    };
    let end = body.find(delimiter)?;
    let frontmatter = &body[..end];

    for line in frontmatter.lines() {
        // YAML: `description: Some text`
        if let Some(rest) = line.strip_prefix("description:") {
            return Some(rest.trim());
        }
        // TOML: `description = "Some text"`
        if let Some(rest) = line.strip_prefix("description") {
            let rest = rest.trim();
            if let Some(rest) = rest.strip_prefix('=') {
                let rest = rest.trim();
                if rest.starts_with('"')
                    && rest.len() > 1
                    && let Some(end) = rest[1..].find('"')
                {
                    return Some(&rest[1..1 + end]);
                }
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_skills_all_have_content() {
        for (name, content) in BUNDLED {
            assert!(!content.is_empty(), "skill '{name}' is empty");
            assert!(content.len() > 100, "skill '{name}' seems too short");
        }
    }

    #[test]
    fn bundled_skills_all_have_descriptions() {
        for (name, content) in BUNDLED {
            assert!(
                extract_description(content).is_some(),
                "skill '{name}' missing frontmatter description"
            );
        }
    }

    #[test]
    fn bundled_count_matches_skills_directory() {
        // 9 skills: git, oci, openspec, python, rust, security, style, typescript, vault
        assert_eq!(BUNDLED.len(), 9);
    }

    #[test]
    fn extract_description_parses_frontmatter() {
        let content = "---\nname: test\ndescription: A test skill\n---\n\n# Test";
        assert_eq!(extract_description(content), Some("A test skill"));
    }

    #[test]
    fn extract_description_returns_none_without_frontmatter() {
        let content = "# No frontmatter here";
        assert_eq!(extract_description(content), None);
    }

    #[test]
    fn extract_description_parses_toml_frontmatter() {
        let content =
            "+++\nid = \"abc\"\nname = \"test\"\ndescription = \"A TOML skill\"\n+++\n\n# Test";
        assert_eq!(extract_description(content), Some("A TOML skill"));
    }

    #[test]
    fn extract_trusted_paths_yaml() {
        let content = "---\nname: test\ntrusted_paths:\n  - ~/Documents/data/\n  - ~/Library/Obsidian/vault/\n---\n\n# Test";
        let paths = extract_trusted_paths(content);
        assert_eq!(paths, vec!["~/Documents/data/", "~/Library/Obsidian/vault/"]);
    }

    #[test]
    fn extract_trusted_paths_toml() {
        let content = "+++\nname = \"test\"\ntrusted_paths = [\"~/Documents/data/\", \"~/vault/\"]\n+++\n\n# Test";
        let paths = extract_trusted_paths(content);
        assert_eq!(paths, vec!["~/Documents/data/", "~/vault/"]);
    }

    #[test]
    fn extract_trusted_paths_empty_when_absent() {
        let content = "---\nname: test\n---\n\n# No trusted paths";
        let paths = extract_trusted_paths(content);
        assert!(paths.is_empty());
    }

    #[test]
    fn extract_trusted_paths_no_frontmatter() {
        let content = "# No frontmatter at all";
        let paths = extract_trusted_paths(content);
        assert!(paths.is_empty());
    }

    #[test]
    fn extract_trusted_paths_yaml_inline() {
        let content = "---\nname: test\ntrusted_paths: [\"~/a/\", \"~/b/\"]\n---\n\n# Test";
        let paths = extract_trusted_paths(content);
        assert_eq!(paths, vec!["~/a/", "~/b/"]);
    }

    #[test]
    fn collect_trusted_paths_deduplicates() {
        let skills = vec![
            "---\ntrusted_paths:\n  - ~/shared/\n---\n".to_string(),
            "---\ntrusted_paths:\n  - ~/shared/\n  - ~/other/\n---\n".to_string(),
        ];
        let paths = collect_trusted_paths(&skills);
        assert_eq!(paths, vec!["~/other/", "~/shared/"]);
    }

    #[test]
    fn extract_phases_from_numbered_skill() {
        let content = "# My Skill\n\n## Phase 0: Setup\nDo setup.\n\n## Phase 1: Execute\nDo the thing.\n\n## Phase 2: Export\nWrite the file.\n";
        let info = extract_phase_info(content).unwrap();
        assert_eq!(info.total_phases, 3);
        assert_eq!(info.final_phase_number, "2");
        assert!(info.final_phase_label.contains("Export"));
    }

    #[test]
    fn extract_phases_fractional() {
        let content = "## Phase 0: Hard Stops\n\n## Phase 0.5: Amendment Check\n\n## Phase 1: Metadata\n\n## Phase 1.5: Response\n\n## Phase 10: Export\n";
        let info = extract_phase_info(content).unwrap();
        assert_eq!(info.total_phases, 5);
        assert_eq!(info.final_phase_number, "10");
        assert!(info.final_phase_label.contains("Export"));
    }

    #[test]
    fn extract_phases_none_when_no_phases() {
        let content = "# Just a Guide\n\nDo things.\n\n## Setup\nSetup stuff.\n";
        assert!(extract_phase_info(content).is_none());
    }

    #[test]
    fn extract_phases_steps() {
        let content = "## Step 1: First\n\n## Step 2: Second\n\n## Step 3: Third\n";
        let info = extract_phase_info(content).unwrap();
        assert_eq!(info.total_phases, 3);
        assert_eq!(info.final_phase_number, "3");
    }

    #[test]
    fn manifest_to_frontmatter_minimal() {
        let manifest = SkillManifest {
            name: "my-skill".into(),
            description: "Does a thing".into(),
            ..Default::default()
        };
        let fm = manifest.to_frontmatter();
        assert!(fm.starts_with("+++"));
        assert!(fm.ends_with("+++"));
        assert!(fm.contains("name = \"my-skill\""));
        assert!(fm.contains("description = \"Does a thing\""));
    }

    #[test]
    fn manifest_to_frontmatter_full() {
        let manifest = SkillManifest {
            name: "opportunity-eval".into(),
            description: "Evaluate govt contracts".into(),
            id: Some("abc-123".into()),
            version: Some("1.0.0".into()),
            tags: vec!["govcon".into()],
            aliases: vec!["eval".into()],
            triggers: vec!["evaluate this".into()],
            trusted_paths: vec!["~/Documents/data/".into()],
            output_path: Some("~/output/".into()),
            output_format: Some("markdown".into()),
            max_turns: Some(100),
            posture: Some("architect".into()),
        };
        let fm = manifest.to_frontmatter();
        assert!(fm.contains("id = \"abc-123\""));
        assert!(fm.contains("version = \"1.0.0\""));
        assert!(fm.contains("tags = [\"govcon\"]"));
        assert!(fm.contains("triggers = [\"evaluate this\"]"));
        assert!(fm.contains("trusted_paths = [\"~/Documents/data/\"]"));
        assert!(fm.contains("output_path = \"~/output/\""));
        assert!(fm.contains("max_turns = 100"));
        assert!(fm.contains("posture = \"architect\""));
    }

    #[test]
    fn manifest_to_skill_file() {
        let manifest = SkillManifest {
            name: "test".into(),
            description: "Test skill".into(),
            ..Default::default()
        };
        let file = manifest.to_skill_file("# My Skill\n\nDo things.\n");
        assert!(file.starts_with("+++"));
        assert!(file.contains("# My Skill"));
    }

    #[test]
    fn list_summary_mentions_bundled_skills() {
        let summary = list_summary().unwrap();
        assert!(summary.contains("Bundled skills"));
        assert!(summary.contains("Run `omegon skills install`"));
    }

    #[test]
    fn parse_skill_file_toml() {
        let content = "+++\nname = \"test\"\ndescription = \"A test\"\nversion = \"1.0.0\"\n+++\n\n# Body\n\nDo things.\n";
        let (manifest, body) = parse_skill_file(content);
        assert_eq!(manifest.name, "test");
        assert_eq!(manifest.description, "A test");
        assert_eq!(manifest.version, Some("1.0.0".into()));
        assert!(body.contains("# Body"));
        assert!(body.contains("Do things."));
    }

    #[test]
    fn parse_skill_file_no_frontmatter() {
        let content = "# Just markdown\n\nNo frontmatter here.\n";
        let (manifest, body) = parse_skill_file(content);
        assert_eq!(manifest.name, "");
        assert!(body.contains("Just markdown"));
    }

    #[test]
    fn split_frontmatter_toml() {
        let content = "+++\nname = \"test\"\n+++\n\nBody here.\n";
        let (fm, body) = split_frontmatter(content);
        assert!(fm.is_some());
        assert!(fm.unwrap().contains("name = \"test\""));
        assert!(body.contains("Body here."));
    }

    #[test]
    fn split_frontmatter_yaml() {
        let content = "---\nname: test\n---\n\nBody here.\n";
        let (fm, body) = split_frontmatter(content);
        assert!(fm.is_some());
        assert!(fm.unwrap().contains("name: test"));
        assert!(body.contains("Body here."));
    }

    #[test]
    fn split_frontmatter_none() {
        let content = "No delimiters here.\n";
        let (fm, body) = split_frontmatter(content);
        assert!(fm.is_none());
        assert_eq!(body, content);
    }

    #[test]
    fn list_structured_includes_bundled() {
        let entries = list_structured().unwrap();
        assert!(entries.iter().any(|e| e.name == "rust" && e.bundled));
        assert!(entries.iter().any(|e| e.name == "git" && e.bundled));
        assert!(entries.iter().any(|e| e.name == "security" && e.bundled));
    }

    #[test]
    fn get_skill_bundled() {
        let (manifest, body, _path) = get_skill("rust").unwrap();
        assert!(!manifest.description.is_empty());
        assert!(!body.is_empty());
    }

    #[test]
    fn get_skill_not_found() {
        let result = get_skill("nonexistent-skill-xyz");
        assert!(result.is_err());
    }

    #[test]
    fn get_skill_traversal_rejected() {
        let result = get_skill("../../../etc/passwd");
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("traversal"));
    }
}
